package com.anysoftkeyboard.janus.app.util

data class SupportedLanguage(
    val code: String,
    val name: String,
    val localName: String,
    val articleCount: Int,
    val pageCount: Int,
    val activeUserCount: Int,
)

val supportedLanguages =
    listOf(
        SupportedLanguage(
            code = "en",
            name = "English",
            localName = "English",
            articleCount = 7133150,
            pageCount = 65060640,
            activeUserCount = 294725,
        ),
        SupportedLanguage(
            code = "ceb",
            name = "Cebuano",
            localName = "Cebuano",
            articleCount = 6115802,
            pageCount = 11232482,
            activeUserCount = 195,
        ),
        SupportedLanguage(
            code = "de",
            name = "German",
            localName = "Deutsch",
            articleCount = 3094716,
            pageCount = 8476933,
            activeUserCount = 41222,
        ),
        SupportedLanguage(
            code = "fr",
            name = "French",
            localName = "français",
            articleCount = 2737425,
            pageCount = 13845568,
            activeUserCount = 41872,
        ),
        SupportedLanguage(
            code = "sv",
            name = "Swedish",
            localName = "svenska",
            articleCount = 2621139,
            pageCount = 6355101,
            activeUserCount = 4938,
        ),
        SupportedLanguage(
            code = "nl",
            name = "Dutch",
            localName = "Nederlands",
            articleCount = 2211032,
            pageCount = 4759213,
            activeUserCount = 9541,
        ),
        SupportedLanguage(
            code = "es",
            name = "Spanish",
            localName = "español",
            articleCount = 2092847,
            pageCount = 8585292,
            activeUserCount = 47213,
        ),
        SupportedLanguage(
            code = "ru",
            name = "Russian",
            localName = "русский",
            articleCount = 2084379,
            pageCount = 8496493,
            activeUserCount = 7849,
        ),
        SupportedLanguage(
            code = "it",
            name = "Italian",
            localName = "italiano",
            articleCount = 1955517,
            pageCount = 8598159,
            activeUserCount = 31509,
        ),
        SupportedLanguage(
            code = "pl",
            name = "Polish",
            localName = "polski",
            articleCount = 1683915,
            pageCount = 3987589,
            activeUserCount = 10717,
        ),
        SupportedLanguage(
            code = "arz",
            name = "Egyptian Arabic",
            localName = "مصرى",
            articleCount = 1630617,
            pageCount = 2223235,
            activeUserCount = 319,
        ),
        SupportedLanguage(
            code = "zh",
            name = "Chinese",
            localName = "中文",
            articleCount = 1522829,
            pageCount = 8314318,
            activeUserCount = 15427,
        ),
        SupportedLanguage(
            code = "ja",
            name = "Japanese",
            localName = "日本語",
            articleCount = 1489013,
            pageCount = 4378538,
            activeUserCount = 25845,
        ),
        SupportedLanguage(
            code = "uk",
            name = "Ukrainian",
            localName = "українська",
            articleCount = 1407338,
            pageCount = 5261296,
            activeUserCount = 5845,
        ),
        SupportedLanguage(
            code = "ar",
            name = "Arabic",
            localName = "العربية",
            articleCount = 1298576,
            pageCount = 9058865,
            activeUserCount = 6674,
        ),
        SupportedLanguage(
            code = "ab",
            name = "Abkhazian",
            localName = "аԥсшәа",
            articleCount = 6488,
            pageCount = 33084,
            activeUserCount = 25,
        ),
        SupportedLanguage(
            code = "ace",
            name = "Acehnese",
            localName = "Acèh",
            articleCount = 13010,
            pageCount = 27979,
            activeUserCount = 49,
        ),
        SupportedLanguage(
            code = "ady",
            name = "Adyghe",
            localName = "адыгабзэ",
            articleCount = 635,
            pageCount = 4817,
            activeUserCount = 19,
        ),
        SupportedLanguage(
            code = "af",
            name = "Afrikaans",
            localName = "Afrikaans",
            articleCount = 127949,
            pageCount = 435132,
            activeUserCount = 309,
        ),
        SupportedLanguage(
            code = "sq",
            name = "Albanian",
            localName = "shqip",
            articleCount = 105199,
            pageCount = 322413,
            activeUserCount = 530,
        ),
        SupportedLanguage(
            code = "als",
            name = "Alemannic",
            localName = "Alemannisch",
            articleCount = 31502,
            pageCount = 74895,
            activeUserCount = 143,
        ),
        SupportedLanguage(
            code = "am",
            name = "Amharic",
            localName = "አማርኛ",
            articleCount = 15571,
            pageCount = 46560,
            activeUserCount = 133,
        ),
        SupportedLanguage(
            code = "ami",
            name = "Amis",
            localName = "Pangcah",
            articleCount = 1146,
            pageCount = 2266,
            activeUserCount = 11,
        ),
        SupportedLanguage(
            code = "anp",
            name = "Angika",
            localName = "अंगिका",
            articleCount = 1671,
            pageCount = 5284,
            activeUserCount = 11,
        ),
        SupportedLanguage(
            code = "an",
            name = "Aragonese",
            localName = "aragonés",
            articleCount = 51253,
            pageCount = 187050,
            activeUserCount = 98,
        ),
        SupportedLanguage(
            code = "rki",
            name = "Arakanese",
            localName = "ရခိုင်",
            articleCount = 1086,
            pageCount = 3242,
            activeUserCount = 15,
        ),
        SupportedLanguage(
            code = "arc",
            name = "Aramaic",
            localName = "ܐܪܡܝܐ",
            articleCount = 1916,
            pageCount = 6354,
            activeUserCount = 17,
        ),
        SupportedLanguage(
            code = "hy",
            name = "Armenian",
            localName = "հայերեն",
            articleCount = 324238,
            pageCount = 1191419,
            activeUserCount = 830,
        ),
        SupportedLanguage(
            code = "roa-rup",
            name = "Aromanian",
            localName = "armãneashti",
            articleCount = 1390,
            pageCount = 4624,
            activeUserCount = 8,
        ),
        SupportedLanguage(
            code = "frp",
            name = "Arpitan",
            localName = "arpetan",
            articleCount = 5820,
            pageCount = 18125,
            activeUserCount = 25,
        ),
        SupportedLanguage(
            code = "as",
            name = "Assamese",
            localName = "অসমীয়া",
            articleCount = 21370,
            pageCount = 119076,
            activeUserCount = 159,
        ),
        SupportedLanguage(
            code = "ast",
            name = "Asturian",
            localName = "asturianu",
            articleCount = 138667,
            pageCount = 248138,
            activeUserCount = 155,
        ),
        SupportedLanguage(
            code = "tay",
            name = "Atayal",
            localName = "Tayal",
            articleCount = 2582,
            pageCount = 3315,
            activeUserCount = 10,
        ),
        SupportedLanguage(
            code = "atj",
            name = "Atikamekw",
            localName = "Atikamekw",
            articleCount = 2078,
            pageCount = 3291,
            activeUserCount = 10,
        ),
        SupportedLanguage(
            code = "av",
            name = "Avaric",
            localName = "авар",
            articleCount = 4008,
            pageCount = 18610,
            activeUserCount = 26,
        ),
        SupportedLanguage(
            code = "awa",
            name = "Awadhi",
            localName = "अवधी",
            articleCount = 2614,
            pageCount = 6844,
            activeUserCount = 26,
        ),
        SupportedLanguage(
            code = "ay",
            name = "Aymara",
            localName = "Aymar aru",
            articleCount = 5253,
            pageCount = 8951,
            activeUserCount = 27,
        ),
        SupportedLanguage(
            code = "az",
            name = "Azerbaijani",
            localName = "azərbaycanca",
            articleCount = 211740,
            pageCount = 654321,
            activeUserCount = 1096,
        ),
        SupportedLanguage(
            code = "ban",
            name = "Balinese",
            localName = "Basa Bali",
            articleCount = 35446,
            pageCount = 73869,
            activeUserCount = 92,
        ),
        SupportedLanguage(
            code = "bm",
            name = "Bambara",
            localName = "bamanankan",
            articleCount = 864,
            pageCount = 3238,
            activeUserCount = 14,
        ),
        SupportedLanguage(
            code = "bn",
            name = "Bangla",
            localName = "বাংলা",
            articleCount = 180990,
            pageCount = 1386567,
            activeUserCount = 2192,
        ),
        SupportedLanguage(
            code = "bjn",
            name = "Banjar",
            localName = "Banjar",
            articleCount = 11570,
            pageCount = 35352,
            activeUserCount = 36,
        ),
        SupportedLanguage(
            code = "map-bms",
            name = "Banyumasan",
            localName = "Basa Banyumasan",
            articleCount = 13941,
            pageCount = 30443,
            activeUserCount = 21,
        ),
        SupportedLanguage(
            code = "ba",
            name = "Bashkir",
            localName = "башҡортса",
            articleCount = 63925,
            pageCount = 183802,
            activeUserCount = 101,
        ),
        SupportedLanguage(
            code = "eu",
            name = "Basque",
            localName = "euskara",
            articleCount = 479937,
            pageCount = 1029607,
            activeUserCount = 915,
        ),
        SupportedLanguage(
            code = "btm",
            name = "Batak Mandailing",
            localName = "Batak Mandailing",
            articleCount = 1199,
            pageCount = 2703,
            activeUserCount = 4,
        ),
        SupportedLanguage(
            code = "bbc",
            name = "Batak Toba",
            localName = "Batak Toba",
            articleCount = 1418,
            pageCount = 2556,
            activeUserCount = 16,
        ),
        SupportedLanguage(
            code = "bar",
            name = "Bavarian",
            localName = "Boarisch",
            articleCount = 27210,
            pageCount = 110658,
            activeUserCount = 59,
        ),
        SupportedLanguage(
            code = "be",
            name = "Belarusian",
            localName = "беларуская",
            articleCount = 261408,
            pageCount = 726719,
            activeUserCount = 468,
        ),
        SupportedLanguage(
            code = "be-tarask",
            name = "Belarusian (Taraškievica orthography)",
            localName = "беларуская (тарашкевіца)",
            articleCount = 90559,
            pageCount = 265321,
            activeUserCount = 200,
        ),
        SupportedLanguage(
            code = "bew",
            name = "Betawi",
            localName = "Betawi",
            articleCount = 3149,
            pageCount = 7588,
            activeUserCount = 34,
        ),
        SupportedLanguage(
            code = "bh",
            name = "Bhojpuri",
            localName = "भोजपुरी",
            articleCount = 8882,
            pageCount = 80909,
            activeUserCount = 40,
        ),
        SupportedLanguage(
            code = "bpy",
            name = "Bishnupriya",
            localName = "বিষ্ণুপ্রিয়া মণিপুরী",
            articleCount = 25092,
            pageCount = 63438,
            activeUserCount = 21,
        ),
        SupportedLanguage(
            code = "bi",
            name = "Bislama",
            localName = "Bislama",
            articleCount = 1486,
            pageCount = 3468,
            activeUserCount = 15,
        ),
        SupportedLanguage(
            code = "bs",
            name = "Bosnian",
            localName = "bosanski",
            articleCount = 96704,
            pageCount = 383136,
            activeUserCount = 308,
        ),
        SupportedLanguage(
            code = "br",
            name = "Breton",
            localName = "brezhoneg",
            articleCount = 90521,
            pageCount = 161126,
            activeUserCount = 125,
        ),
        SupportedLanguage(
            code = "bug",
            name = "Buginese",
            localName = "Basa Ugi",
            articleCount = 15953,
            pageCount = 20454,
            activeUserCount = 13,
        ),
        SupportedLanguage(
            code = "bg",
            name = "Bulgarian",
            localName = "български",
            articleCount = 307554,
            pageCount = 697071,
            activeUserCount = 2088,
        ),
        SupportedLanguage(
            code = "my",
            name = "Burmese",
            localName = "မြန်မာဘာသာ",
            articleCount = 110139,
            pageCount = 264081,
            activeUserCount = 322,
        ),
        SupportedLanguage(
            code = "zh-yue",
            name = "Cantonese",
            localName = "粵語",
            articleCount = 149170,
            pageCount = 337196,
            activeUserCount = 936,
        ),
        SupportedLanguage(
            code = "ca",
            name = "Catalan",
            localName = "català",
            articleCount = 788490,
            pageCount = 1980442,
            activeUserCount = 2536,
        ),
        SupportedLanguage(
            code = "bcl",
            name = "Central Bikol",
            localName = "Bikol Central",
            articleCount = 21413,
            pageCount = 50369,
            activeUserCount = 65,
        ),
        SupportedLanguage(
            code = "dtp",
            name = "Central Dusun",
            localName = "Kadazandusun",
            articleCount = 1773,
            pageCount = 7359,
            activeUserCount = 53,
        ),
        SupportedLanguage(
            code = "knc",
            name = "Central Kanuri",
            localName = "Yerwa Kanuri",
            articleCount = 1624,
            pageCount = 2538,
            activeUserCount = 15,
        ),
        SupportedLanguage(
            code = "ckb",
            name = "Central Kurdish",
            localName = "کوردی",
            articleCount = 79665,
            pageCount = 252570,
            activeUserCount = 198,
        ),
        SupportedLanguage(
            code = "ch",
            name = "Chamorro",
            localName = "Chamoru",
            articleCount = 559,
            pageCount = 2572,
            activeUserCount = 22,
        ),
        SupportedLanguage(
            code = "cbk-zam",
            name = "Chavacano",
            localName = "Chavacano de Zamboanga",
            articleCount = 3235,
            pageCount = 8985,
            activeUserCount = 23,
        ),
        SupportedLanguage(
            code = "ce",
            name = "Chechen",
            localName = "нохчийн",
            articleCount = 817961,
            pageCount = 1655973,
            activeUserCount = 56,
        ),
        SupportedLanguage(
            code = "chr",
            name = "Cherokee",
            localName = "ᏣᎳᎩ",
            articleCount = 987,
            pageCount = 4014,
            activeUserCount = 25,
        ),
        SupportedLanguage(
            code = "chy",
            name = "Cheyenne",
            localName = "Tsetsêhestâhese",
            articleCount = 721,
            pageCount = 2299,
            activeUserCount = 9,
        ),
        SupportedLanguage(
            code = "cu",
            name = "Church Slavic",
            localName = "словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ",
            articleCount = 1333,
            pageCount = 5903,
            activeUserCount = 35,
        ),
        SupportedLanguage(
            code = "cv",
            name = "Chuvash",
            localName = "чӑвашла",
            articleCount = 58521,
            pageCount = 121978,
            activeUserCount = 79,
        ),
        SupportedLanguage(
            code = "ksh",
            name = "Colognian",
            localName = "Ripoarisch",
            articleCount = 3038,
            pageCount = 10817,
            activeUserCount = 19,
        ),
        SupportedLanguage(
            code = "kw",
            name = "Cornish",
            localName = "kernowek",
            articleCount = 7101,
            pageCount = 14816,
            activeUserCount = 25,
        ),
        SupportedLanguage(
            code = "co",
            name = "Corsican",
            localName = "corsu",
            articleCount = 8636,
            pageCount = 17838,
            activeUserCount = 51,
        ),
        SupportedLanguage(
            code = "crh",
            name = "Crimean Tatar",
            localName = "qırımtatarca",
            articleCount = 29643,
            pageCount = 57727,
            activeUserCount = 45,
        ),
        SupportedLanguage(
            code = "hr",
            name = "Croatian",
            localName = "hrvatski",
            articleCount = 229301,
            pageCount = 496193,
            activeUserCount = 1224,
        ),
        SupportedLanguage(
            code = "cs",
            name = "Czech",
            localName = "čeština",
            articleCount = 585916,
            pageCount = 1632989,
            activeUserCount = 5995,
        ),
        SupportedLanguage(
            code = "dag",
            name = "Dagbani",
            localName = "dagbanli",
            articleCount = 13437,
            pageCount = 24433,
            activeUserCount = 49,
        ),
        SupportedLanguage(
            code = "da",
            name = "Danish",
            localName = "dansk",
            articleCount = 312543,
            pageCount = 980467,
            activeUserCount = 1841,
        ),
        SupportedLanguage(
            code = "diq",
            name = "Dimli",
            localName = "Zazaki",
            articleCount = 42604,
            pageCount = 64190,
            activeUserCount = 52,
        ),
        SupportedLanguage(
            code = "din",
            name = "Dinka",
            localName = "Thuɔŋjäŋ",
            articleCount = 323,
            pageCount = 1063,
            activeUserCount = 12,
        ),
        SupportedLanguage(
            code = "dv",
            name = "Divehi",
            localName = "ދިވެހިބަސް",
            articleCount = 3196,
            pageCount = 12526,
            activeUserCount = 22,
        ),
        SupportedLanguage(
            code = "dty",
            name = "Doteli",
            localName = "डोटेली",
            articleCount = 3641,
            pageCount = 22337,
            activeUserCount = 19,
        ),
        SupportedLanguage(
            code = "dz",
            name = "Dzongkha",
            localName = "ཇོང་ཁ",
            articleCount = 418,
            pageCount = 5700,
            activeUserCount = 28,
        ),
        SupportedLanguage(
            code = "mhr",
            name = "Eastern Mari",
            localName = "олык марий",
            articleCount = 11325,
            pageCount = 31425,
            activeUserCount = 23,
        ),
        SupportedLanguage(
            code = "eml",
            name = "Emiliano-Romagnolo",
            localName = "emiliàn e rumagnòl",
            articleCount = 13866,
            pageCount = 37083,
            activeUserCount = 32,
        ),
        SupportedLanguage(
            code = "myv",
            name = "Erzya",
            localName = "эрзянь",
            articleCount = 7871,
            pageCount = 31630,
            activeUserCount = 23,
        ),
        SupportedLanguage(
            code = "eo",
            name = "Esperanto",
            localName = "Esperanto",
            articleCount = 381508,
            pageCount = 856255,
            activeUserCount = 409,
        ),
        SupportedLanguage(
            code = "et",
            name = "Estonian",
            localName = "eesti",
            articleCount = 257595,
            pageCount = 607696,
            activeUserCount = 1310,
        ),
        SupportedLanguage(
            code = "ee",
            name = "Ewe",
            localName = "eʋegbe",
            articleCount = 1267,
            pageCount = 4193,
            activeUserCount = 13,
        ),
        SupportedLanguage(
            code = "ext",
            name = "Extremaduran",
            localName = "estremeñu",
            articleCount = 4146,
            pageCount = 9282,
            activeUserCount = 31,
        ),
        SupportedLanguage(
            code = "fat",
            name = "Fanti",
            localName = "mfantse",
            articleCount = 1757,
            pageCount = 4723,
            activeUserCount = 18,
        ),
        SupportedLanguage(
            code = "fo",
            name = "Faroese",
            localName = "føroyskt",
            articleCount = 14193,
            pageCount = 41037,
            activeUserCount = 39,
        ),
        SupportedLanguage(
            code = "hif",
            name = "Fiji Hindi",
            localName = "Fiji Hindi",
            articleCount = 12143,
            pageCount = 55881,
            activeUserCount = 80,
        ),
        SupportedLanguage(
            code = "fj",
            name = "Fijian",
            localName = "Na Vosa Vakaviti",
            articleCount = 1693,
            pageCount = 4487,
            activeUserCount = 12,
        ),
        SupportedLanguage(
            code = "fi",
            name = "Finnish",
            localName = "suomi",
            articleCount = 612813,
            pageCount = 1570623,
            activeUserCount = 3820,
        ),
        SupportedLanguage(
            code = "fon",
            name = "Fon",
            localName = "fɔ̀ngbè",
            articleCount = 3469,
            pageCount = 5214,
            activeUserCount = 17,
        ),
        SupportedLanguage(
            code = "gur",
            name = "Frafra",
            localName = "farefare",
            articleCount = 1329,
            pageCount = 2547,
            activeUserCount = 20,
        ),
        SupportedLanguage(
            code = "fur",
            name = "Friulian",
            localName = "furlan",
            articleCount = 4921,
            pageCount = 11185,
            activeUserCount = 30,
        ),
        SupportedLanguage(
            code = "ff",
            name = "Fula",
            localName = "Fulfulde",
            articleCount = 13938,
            pageCount = 28752,
            activeUserCount = 46,
        ),
        SupportedLanguage(
            code = "gag",
            name = "Gagauz",
            localName = "Gagauz",
            articleCount = 3013,
            pageCount = 7659,
            activeUserCount = 32,
        ),
        SupportedLanguage(
            code = "gl",
            name = "Galician",
            localName = "galego",
            articleCount = 229643,
            pageCount = 565803,
            activeUserCount = 485,
        ),
        SupportedLanguage(
            code = "gan",
            name = "Gan",
            localName = "贛語",
            articleCount = 6816,
            pageCount = 34478,
            activeUserCount = 31,
        ),
        SupportedLanguage(
            code = "lg",
            name = "Ganda",
            localName = "Luganda",
            articleCount = 4496,
            pageCount = 8857,
            activeUserCount = 30,
        ),
        SupportedLanguage(
            code = "ka",
            name = "Georgian",
            localName = "ქართული",
            articleCount = 190431,
            pageCount = 751312,
            activeUserCount = 479,
        ),
        SupportedLanguage(
            code = "gpe",
            name = "Ghanaian Pidgin",
            localName = "Ghanaian Pidgin",
            articleCount = 4390,
            pageCount = 22987,
            activeUserCount = 26,
        ),
        SupportedLanguage(
            code = "glk",
            name = "Gilaki",
            localName = "گیلکی",
            articleCount = 48301,
            pageCount = 57617,
            activeUserCount = 26,
        ),
        SupportedLanguage(
            code = "gom",
            name = "Goan Konkani",
            localName = "गोंयची कोंकणी / Gõychi Konknni",
            articleCount = 3641,
            pageCount = 8912,
            activeUserCount = 16,
        ),
        SupportedLanguage(
            code = "gor",
            name = "Gorontalo",
            localName = "Bahasa Hulontalo",
            articleCount = 15015,
            pageCount = 24704,
            activeUserCount = 52,
        ),
        SupportedLanguage(
            code = "got",
            name = "Gothic",
            localName = "𐌲𐌿𐍄𐌹𐍃𐌺",
            articleCount = 1006,
            pageCount = 3982,
            activeUserCount = 18,
        ),
        SupportedLanguage(
            code = "el",
            name = "Greek",
            localName = "Ελληνικά",
            articleCount = 264154,
            pageCount = 742835,
            activeUserCount = 2703,
        ),
        SupportedLanguage(
            code = "gn",
            name = "Guarani",
            localName = "Avañe'ẽ",
            articleCount = 6000,
            pageCount = 14092,
            activeUserCount = 31,
        ),
        SupportedLanguage(
            code = "gcr",
            name = "Guianan Creole",
            localName = "kriyòl gwiyannen",
            articleCount = 1075,
            pageCount = 2672,
            activeUserCount = 6,
        ),
        SupportedLanguage(
            code = "gu",
            name = "Gujarati",
            localName = "ગુજરાતી",
            articleCount = 30797,
            pageCount = 135388,
            activeUserCount = 119,
        ),
        SupportedLanguage(
            code = "guw",
            name = "Gun",
            localName = "gungbe",
            articleCount = 1568,
            pageCount = 2788,
            activeUserCount = 10,
        ),
        SupportedLanguage(
            code = "ht",
            name = "Haitian Creole",
            localName = "Kreyòl ayisyen",
            articleCount = 71511,
            pageCount = 92999,
            activeUserCount = 88,
        ),
        SupportedLanguage(
            code = "hak",
            name = "Hakka Chinese",
            localName = "客家語 / Hak-kâ-ngî",
            articleCount = 10393,
            pageCount = 19939,
            activeUserCount = 34,
        ),
        SupportedLanguage(
            code = "ha",
            name = "Hausa",
            localName = "Hausa",
            articleCount = 88914,
            pageCount = 129556,
            activeUserCount = 234,
        ),
        SupportedLanguage(
            code = "haw",
            name = "Hawaiian",
            localName = "Hawaiʻi",
            articleCount = 2973,
            pageCount = 6229,
            activeUserCount = 26,
        ),
        SupportedLanguage(
            code = "he",
            name = "Hebrew",
            localName = "עברית",
            articleCount = 390250,
            pageCount = 1640113,
            activeUserCount = 8306,
        ),
        SupportedLanguage(
            code = "hi",
            name = "Hindi",
            localName = "हिन्दी",
            articleCount = 167402,
            pageCount = 1384323,
            activeUserCount = 1180,
        ),
        SupportedLanguage(
            code = "hu",
            name = "Hungarian",
            localName = "magyar",
            articleCount = 566096,
            pageCount = 1608550,
            activeUserCount = 3600,
        ),
        SupportedLanguage(
            code = "iba",
            name = "Iban",
            localName = "Jaku Iban",
            articleCount = 2068,
            pageCount = 5690,
            activeUserCount = 23,
        ),
        SupportedLanguage(
            code = "is",
            name = "Icelandic",
            localName = "íslenska",
            articleCount = 61163,
            pageCount = 159609,
            activeUserCount = 335,
        ),
        SupportedLanguage(
            code = "io",
            name = "Ido",
            localName = "Ido",
            articleCount = 60785,
            pageCount = 94401,
            activeUserCount = 74,
        ),
        SupportedLanguage(
            code = "igl",
            name = "Igala",
            localName = "Igala",
            articleCount = 945,
            pageCount = 1360,
            activeUserCount = 8,
        ),
        SupportedLanguage(
            code = "ig",
            name = "Igbo",
            localName = "Igbo",
            articleCount = 44269,
            pageCount = 61138,
            activeUserCount = 89,
        ),
        SupportedLanguage(
            code = "ilo",
            name = "Iloko",
            localName = "Ilokano",
            articleCount = 15448,
            pageCount = 70567,
            activeUserCount = 25,
        ),
        SupportedLanguage(
            code = "smn",
            name = "Inari Sami",
            localName = "anarâškielâ",
            articleCount = 6517,
            pageCount = 29243,
            activeUserCount = 20,
        ),
        SupportedLanguage(
            code = "id",
            name = "Indonesian",
            localName = "Bahasa Indonesia",
            articleCount = 763244,
            pageCount = 4210300,
            activeUserCount = 5603,
        ),
        SupportedLanguage(
            code = "inh",
            name = "Ingush",
            localName = "гӀалгӀай",
            articleCount = 2503,
            pageCount = 16831,
            activeUserCount = 21,
        ),
        SupportedLanguage(
            code = "ia",
            name = "Interlingua",
            localName = "interlingua",
            articleCount = 30189,
            pageCount = 46109,
            activeUserCount = 54,
        ),
        SupportedLanguage(
            code = "ie",
            name = "Interlingue",
            localName = "Interlingue",
            articleCount = 13458,
            pageCount = 17758,
            activeUserCount = 38,
        ),
        SupportedLanguage(
            code = "iu",
            name = "Inuktitut",
            localName = "ᐃᓄᒃᑎᑐᑦ / inuktitut",
            articleCount = 425,
            pageCount = 2945,
            activeUserCount = 27,
        ),
        SupportedLanguage(
            code = "ik",
            name = "Inupiaq",
            localName = "Iñupiatun",
            articleCount = 594,
            pageCount = 2764,
            activeUserCount = 12,
        ),
        SupportedLanguage(
            code = "ga",
            name = "Irish",
            localName = "Gaeilge",
            articleCount = 62914,
            pageCount = 113161,
            activeUserCount = 110,
        ),
        SupportedLanguage(
            code = "jam",
            name = "Jamaican Creole English",
            localName = "Patois",
            articleCount = 1732,
            pageCount = 3135,
            activeUserCount = 15,
        ),
        SupportedLanguage(
            code = "jv",
            name = "Javanese",
            localName = "Jawa",
            articleCount = 74926,
            pageCount = 185903,
            activeUserCount = 133,
        ),
        SupportedLanguage(
            code = "kaj",
            name = "Jju",
            localName = "Jju",
            articleCount = 216,
            pageCount = 1120,
            activeUserCount = 16,
        ),
        SupportedLanguage(
            code = "kbd",
            name = "Kabardian",
            localName = "адыгэбзэ",
            articleCount = 1640,
            pageCount = 7097,
            activeUserCount = 13,
        ),
        SupportedLanguage(
            code = "kbp",
            name = "Kabiye",
            localName = "Kabɩyɛ",
            articleCount = 1714,
            pageCount = 3448,
            activeUserCount = 7,
        ),
        SupportedLanguage(
            code = "kab",
            name = "Kabyle",
            localName = "Taqbaylit",
            articleCount = 7013,
            pageCount = 17911,
            activeUserCount = 26,
        ),
        SupportedLanguage(
            code = "xal",
            name = "Kalmyk",
            localName = "хальмг",
            articleCount = 1587,
            pageCount = 12414,
            activeUserCount = 22,
        ),
        SupportedLanguage(
            code = "kn",
            name = "Kannada",
            localName = "ಕನ್ನಡ",
            articleCount = 34514,
            pageCount = 158656,
            activeUserCount = 216,
        ),
        SupportedLanguage(
            code = "kaa",
            name = "Kara-Kalpak",
            localName = "Qaraqalpaqsha",
            articleCount = 11291,
            pageCount = 30935,
            activeUserCount = 58,
        ),
        SupportedLanguage(
            code = "krc",
            name = "Karachay-Balkar",
            localName = "къарачай-малкъар",
            articleCount = 2737,
            pageCount = 16979,
            activeUserCount = 17,
        ),
        SupportedLanguage(
            code = "ks",
            name = "Kashmiri",
            localName = "کٲشُر",
            articleCount = 8792,
            pageCount = 21645,
            activeUserCount = 30,
        ),
        SupportedLanguage(
            code = "csb",
            name = "Kashubian",
            localName = "kaszëbsczi",
            articleCount = 5517,
            pageCount = 8937,
            activeUserCount = 30,
        ),
        SupportedLanguage(
            code = "kk",
            name = "Kazakh",
            localName = "қазақша",
            articleCount = 242416,
            pageCount = 661401,
            activeUserCount = 462,
        ),
        SupportedLanguage(
            code = "km",
            name = "Khmer",
            localName = "ភាសាខ្មែរ",
            articleCount = 11948,
            pageCount = 36910,
            activeUserCount = 192,
        ),
        SupportedLanguage(
            code = "ki",
            name = "Kikuyu",
            localName = "Gĩkũyũ",
            articleCount = 2090,
            pageCount = 3882,
            activeUserCount = 14,
        ),
        SupportedLanguage(
            code = "rw",
            name = "Kinyarwanda",
            localName = "Ikinyarwanda",
            articleCount = 8939,
            pageCount = 17749,
            activeUserCount = 49,
        ),
        SupportedLanguage(
            code = "kge",
            name = "Komering",
            localName = "Kumoring",
            articleCount = 2878,
            pageCount = 4614,
            activeUserCount = 8,
        ),
        SupportedLanguage(
            code = "kv",
            name = "Komi",
            localName = "коми",
            articleCount = 5739,
            pageCount = 19677,
            activeUserCount = 25,
        ),
        SupportedLanguage(
            code = "koi",
            name = "Komi-Permyak",
            localName = "перем коми",
            articleCount = 3469,
            pageCount = 13584,
            activeUserCount = 7,
        ),
        SupportedLanguage(
            code = "kg",
            name = "Kongo",
            localName = "Kongo",
            articleCount = 1579,
            pageCount = 4044,
            activeUserCount = 17,
        ),
        SupportedLanguage(
            code = "ko",
            name = "Korean",
            localName = "한국어",
            articleCount = 737631,
            pageCount = 3502892,
            activeUserCount = 5693,
        ),
        SupportedLanguage(
            code = "avk",
            name = "Kotava",
            localName = "Kotava",
            articleCount = 29900,
            pageCount = 36353,
            activeUserCount = 16,
        ),
        SupportedLanguage(
            code = "ku",
            name = "Kurdish",
            localName = "kurdî",
            articleCount = 90996,
            pageCount = 291070,
            activeUserCount = 130,
        ),
        SupportedLanguage(
            code = "kus",
            name = "Kusaal",
            localName = "Kʋsaal",
            articleCount = 1261,
            pageCount = 1859,
            activeUserCount = 8,
        ),
        SupportedLanguage(
            code = "ky",
            name = "Kyrgyz",
            localName = "кыргызча",
            articleCount = 76158,
            pageCount = 122452,
            activeUserCount = 136,
        ),
        SupportedLanguage(
            code = "lld",
            name = "Ladin",
            localName = "Ladin",
            articleCount = 180840,
            pageCount = 188224,
            activeUserCount = 37,
        ),
        SupportedLanguage(
            code = "lad",
            name = "Ladino",
            localName = "Ladino",
            articleCount = 3924,
            pageCount = 12681,
            activeUserCount = 27,
        ),
        SupportedLanguage(
            code = "lbe",
            name = "Lak",
            localName = "лакку",
            articleCount = 1090,
            pageCount = 16065,
            activeUserCount = 12,
        ),
        SupportedLanguage(
            code = "lo",
            name = "Lao",
            localName = "ລາວ",
            articleCount = 5449,
            pageCount = 15984,
            activeUserCount = 69,
        ),
        SupportedLanguage(
            code = "ltg",
            name = "Latgalian",
            localName = "latgaļu",
            articleCount = 1118,
            pageCount = 3217,
            activeUserCount = 14,
        ),
        SupportedLanguage(
            code = "la",
            name = "Latin",
            localName = "Latina",
            articleCount = 141016,
            pageCount = 292395,
            activeUserCount = 225,
        ),
        SupportedLanguage(
            code = "lv",
            name = "Latvian",
            localName = "latviešu",
            articleCount = 140706,
            pageCount = 562774,
            activeUserCount = 756,
        ),
        SupportedLanguage(
            code = "lez",
            name = "Lezghian",
            localName = "лезги",
            articleCount = 4456,
            pageCount = 14992,
            activeUserCount = 18,
        ),
        SupportedLanguage(
            code = "lij",
            name = "Ligurian",
            localName = "Ligure",
            articleCount = 11480,
            pageCount = 28229,
            activeUserCount = 37,
        ),
        SupportedLanguage(
            code = "li",
            name = "Limburgish",
            localName = "Limburgs",
            articleCount = 15155,
            pageCount = 68676,
            activeUserCount = 47,
        ),
        SupportedLanguage(
            code = "ln",
            name = "Lingala",
            localName = "lingála",
            articleCount = 4886,
            pageCount = 11523,
            activeUserCount = 26,
        ),
        SupportedLanguage(
            code = "lfn",
            name = "Lingua Franca Nova",
            localName = "Lingua Franca Nova",
            articleCount = 4503,
            pageCount = 7218,
            activeUserCount = 29,
        ),
        SupportedLanguage(
            code = "zh-classical",
            name = "Literary Chinese",
            localName = "文言",
            articleCount = 13964,
            pageCount = 119454,
            activeUserCount = 78,
        ),
        SupportedLanguage(
            code = "lt",
            name = "Lithuanian",
            localName = "lietuvių",
            articleCount = 224927,
            pageCount = 562121,
            activeUserCount = 848,
        ),
        SupportedLanguage(
            code = "olo",
            name = "Livvi-Karelian",
            localName = "livvinkarjala",
            articleCount = 4676,
            pageCount = 14171,
            activeUserCount = 15,
        ),
        SupportedLanguage(
            code = "jbo",
            name = "Lojban",
            localName = "la .lojban.",
            articleCount = 1352,
            pageCount = 5813,
            activeUserCount = 17,
        ),
        SupportedLanguage(
            code = "lmo",
            name = "Lombard",
            localName = "lombard",
            articleCount = 79974,
            pageCount = 152920,
            activeUserCount = 75,
        ),
        SupportedLanguage(
            code = "nds",
            name = "Low German",
            localName = "Plattdüütsch",
            articleCount = 85792,
            pageCount = 185851,
            activeUserCount = 53,
        ),
        SupportedLanguage(
            code = "nds-nl",
            name = "Low Saxon",
            localName = "Nedersaksies",
            articleCount = 8077,
            pageCount = 21983,
            activeUserCount = 57,
        ),
        SupportedLanguage(
            code = "dsb",
            name = "Lower Sorbian",
            localName = "dolnoserbski",
            articleCount = 3442,
            pageCount = 11645,
            activeUserCount = 29,
        ),
        SupportedLanguage(
            code = "lb",
            name = "Luxembourgish",
            localName = "Lëtzebuergesch",
            articleCount = 66588,
            pageCount = 141141,
            activeUserCount = 139,
        ),
        SupportedLanguage(
            code = "mk",
            name = "Macedonian",
            localName = "македонски",
            articleCount = 158413,
            pageCount = 594092,
            activeUserCount = 347,
        ),
        SupportedLanguage(
            code = "mad",
            name = "Madurese",
            localName = "Madhurâ",
            articleCount = 5043,
            pageCount = 15452,
            activeUserCount = 72,
        ),
        SupportedLanguage(
            code = "mai",
            name = "Maithili",
            localName = "मैथिली",
            articleCount = 14238,
            pageCount = 45562,
            activeUserCount = 37,
        ),
        SupportedLanguage(
            code = "mg",
            name = "Malagasy",
            localName = "Malagasy",
            articleCount = 102053,
            pageCount = 259571,
            activeUserCount = 75,
        ),
        SupportedLanguage(
            code = "ms",
            name = "Malay",
            localName = "Bahasa Melayu",
            articleCount = 436454,
            pageCount = 1175135,
            activeUserCount = 2268,
        ),
        SupportedLanguage(
            code = "ml",
            name = "Malayalam",
            localName = "മലയാളം",
            articleCount = 87692,
            pageCount = 550540,
            activeUserCount = 468,
        ),
        SupportedLanguage(
            code = "mt",
            name = "Maltese",
            localName = "Malti",
            articleCount = 7714,
            pageCount = 23606,
            activeUserCount = 65,
        ),
        SupportedLanguage(
            code = "mni",
            name = "Manipuri",
            localName = "ꯃꯤꯇꯩ ꯂꯣꯟ",
            articleCount = 10459,
            pageCount = 17440,
            activeUserCount = 34,
        ),
        SupportedLanguage(
            code = "gv",
            name = "Manx",
            localName = "Gaelg",
            articleCount = 7080,
            pageCount = 41229,
            activeUserCount = 17,
        ),
        SupportedLanguage(
            code = "mr",
            name = "Marathi",
            localName = "मराठी",
            articleCount = 101259,
            pageCount = 328260,
            activeUserCount = 419,
        ),
        SupportedLanguage(
            code = "mzn",
            name = "Mazanderani",
            localName = "مازِرونی",
            articleCount = 64570,
            pageCount = 107437,
            activeUserCount = 45,
        ),
        SupportedLanguage(
            code = "min",
            name = "Minangkabau",
            localName = "Minangkabau",
            articleCount = 228825,
            pageCount = 473859,
            activeUserCount = 71,
        ),
        SupportedLanguage(
            code = "cdo",
            name = "Mindong",
            localName = "閩東語 / Mìng-dĕ̤ng-ngṳ̄",
            articleCount = 16705,
            pageCount = 33547,
            activeUserCount = 27,
        ),
        SupportedLanguage(
            code = "xmf",
            name = "Mingrelian",
            localName = "მარგალური",
            articleCount = 22094,
            pageCount = 41869,
            activeUserCount = 37,
        ),
        SupportedLanguage(
            code = "zh-min-nan",
            name = "Minnan",
            localName = "閩南語 / Bân-lâm-gí",
            articleCount = 433911,
            pageCount = 1076163,
            activeUserCount = 109,
        ),
        SupportedLanguage(
            code = "mwl",
            name = "Mirandese",
            localName = "Mirandés",
            articleCount = 4285,
            pageCount = 10710,
            activeUserCount = 23,
        ),
        SupportedLanguage(
            code = "mdf",
            name = "Moksha",
            localName = "мокшень",
            articleCount = 7621,
            pageCount = 23856,
            activeUserCount = 18,
        ),
        SupportedLanguage(
            code = "mnw",
            name = "Mon",
            localName = "ဘာသာမန်",
            articleCount = 1973,
            pageCount = 6818,
            activeUserCount = 17,
        ),
        SupportedLanguage(
            code = "mn",
            name = "Mongolian",
            localName = "монгол",
            articleCount = 27007,
            pageCount = 114331,
            activeUserCount = 283,
        ),
        SupportedLanguage(
            code = "ary",
            name = "Moroccan Arabic",
            localName = "الدارجة",
            articleCount = 11164,
            pageCount = 92267,
            activeUserCount = 67,
        ),
        SupportedLanguage(
            code = "mos",
            name = "Mossi",
            localName = "moore",
            articleCount = 1312,
            pageCount = 2100,
            activeUserCount = 15,
        ),
        SupportedLanguage(
            code = "mi",
            name = "Māori",
            localName = "Māori",
            articleCount = 8027,
            pageCount = 15398,
            activeUserCount = 36,
        ),
        SupportedLanguage(
            code = "nah",
            name = "Nahuatl",
            localName = "Nāhuatl",
            articleCount = 4163,
            pageCount = 13084,
            activeUserCount = 26,
        ),
        SupportedLanguage(
            code = "nv",
            name = "Navajo",
            localName = "Diné bizaad",
            articleCount = 22664,
            pageCount = 36566,
            activeUserCount = 19,
        ),
        SupportedLanguage(
            code = "ppl",
            name = "Nawat",
            localName = "Nawat",
            articleCount = 236,
            pageCount = 1195,
            activeUserCount = 15,
        ),
        SupportedLanguage(
            code = "nap",
            name = "Neapolitan",
            localName = "Napulitano",
            articleCount = 14945,
            pageCount = 24184,
            activeUserCount = 36,
        ),
        SupportedLanguage(
            code = "ne",
            name = "Nepali",
            localName = "नेपाली",
            articleCount = 29457,
            pageCount = 112608,
            activeUserCount = 224,
        ),
        SupportedLanguage(
            code = "new",
            name = "Newari",
            localName = "नेपाल भाषा",
            articleCount = 73419,
            pageCount = 264269,
            activeUserCount = 32,
        ),
        SupportedLanguage(
            code = "nia",
            name = "Nias",
            localName = "Li Niha",
            articleCount = 1766,
            pageCount = 4468,
            activeUserCount = 9,
        ),
        SupportedLanguage(
            code = "pcm",
            name = "Nigerian Pidgin",
            localName = "Naijá",
            articleCount = 1538,
            pageCount = 2799,
            activeUserCount = 15,
        ),
        SupportedLanguage(
            code = "nrm",
            name = "Norman",
            localName = "Nouormand",
            articleCount = 5058,
            pageCount = 10690,
            activeUserCount = 20,
        ),
        SupportedLanguage(
            code = "frr",
            name = "Northern Frisian",
            localName = "Nordfriisk",
            articleCount = 20832,
            pageCount = 51764,
            activeUserCount = 33,
        ),
        SupportedLanguage(
            code = "se",
            name = "Northern Sami",
            localName = "davvisámegiella",
            articleCount = 7908,
            pageCount = 21125,
            activeUserCount = 22,
        ),
        SupportedLanguage(
            code = "nso",
            name = "Northern Sotho",
            localName = "Sesotho sa Leboa",
            articleCount = 8787,
            pageCount = 11501,
            activeUserCount = 12,
        ),
        SupportedLanguage(
            code = "no",
            name = "Norwegian",
            localName = "norsk",
            articleCount = 671368,
            pageCount = 1890290,
            activeUserCount = 2666,
        ),
        SupportedLanguage(
            code = "nn",
            name = "Norwegian Nynorsk",
            localName = "norsk nynorsk",
            articleCount = 177225,
            pageCount = 399245,
            activeUserCount = 240,
        ),
        SupportedLanguage(
            code = "nov",
            name = "Novial",
            localName = "Novial",
            articleCount = 2068,
            pageCount = 5173,
            activeUserCount = 22,
        ),
        SupportedLanguage(
            code = "nup",
            name = "Nupe",
            localName = "Nupe",
            articleCount = 604,
            pageCount = 1417,
            activeUserCount = 18,
        ),
        SupportedLanguage(
            code = "ny",
            name = "Nyanja",
            localName = "Chi-Chewa",
            articleCount = 1099,
            pageCount = 5358,
            activeUserCount = 12,
        ),
        SupportedLanguage(
            code = "nqo",
            name = "N’Ko",
            localName = "ߒߞߏ",
            articleCount = 1587,
            pageCount = 3443,
            activeUserCount = 9,
        ),
        SupportedLanguage(
            code = "ann",
            name = "Obolo",
            localName = "Obolo",
            articleCount = 433,
            pageCount = 893,
            activeUserCount = 10,
        ),
        SupportedLanguage(
            code = "oc",
            name = "Occitan",
            localName = "occitan",
            articleCount = 90569,
            pageCount = 166693,
            activeUserCount = 181,
        ),
        SupportedLanguage(
            code = "or",
            name = "Odia",
            localName = "ଓଡ଼ିଆ",
            articleCount = 20357,
            pageCount = 86155,
            activeUserCount = 72,
        ),
        SupportedLanguage(
            code = "ang",
            name = "Old English",
            localName = "Ænglisc",
            articleCount = 5145,
            pageCount = 21792,
            activeUserCount = 61,
        ),
        SupportedLanguage(
            code = "om",
            name = "Oromo",
            localName = "Oromoo",
            articleCount = 1962,
            pageCount = 5335,
            activeUserCount = 30,
        ),
        SupportedLanguage(
            code = "os",
            name = "Ossetic",
            localName = "ирон",
            articleCount = 21539,
            pageCount = 76993,
            activeUserCount = 30,
        ),
        SupportedLanguage(
            code = "blk",
            name = "Pa'O",
            localName = "ပအိုဝ်ႏဘာႏသာႏ",
            articleCount = 2910,
            pageCount = 8892,
            activeUserCount = 14,
        ),
        SupportedLanguage(
            code = "pwn",
            name = "Paiwan",
            localName = "pinayuanan",
            articleCount = 376,
            pageCount = 636,
            activeUserCount = 9,
        ),
        SupportedLanguage(
            code = "pfl",
            name = "Palatine German",
            localName = "Pälzisch",
            articleCount = 2840,
            pageCount = 7087,
            activeUserCount = 11,
        ),
        SupportedLanguage(
            code = "pi",
            name = "Pali",
            localName = "पालि",
            articleCount = 301,
            pageCount = 1830,
            activeUserCount = 8,
        ),
        SupportedLanguage(
            code = "pam",
            name = "Pampanga",
            localName = "Kapampangan",
            articleCount = 10208,
            pageCount = 23334,
            activeUserCount = 19,
        ),
        SupportedLanguage(
            code = "pag",
            name = "Pangasinan",
            localName = "Pangasinan",
            articleCount = 2616,
            pageCount = 6738,
            activeUserCount = 11,
        ),
        SupportedLanguage(
            code = "rsk",
            name = "Pannonian Rusyn",
            localName = "руски",
            articleCount = 1112,
            pageCount = 2441,
            activeUserCount = 23,
        ),
        SupportedLanguage(
            code = "pap",
            name = "Papiamento",
            localName = "Papiamentu",
            articleCount = 5241,
            pageCount = 10794,
            activeUserCount = 28,
        ),
        SupportedLanguage(
            code = "ps",
            name = "Pashto",
            localName = "پښتو",
            articleCount = 21148,
            pageCount = 76043,
            activeUserCount = 75,
        ),
        SupportedLanguage(
            code = "pdc",
            name = "Pennsylvania German",
            localName = "Deitsch",
            articleCount = 2049,
            pageCount = 5926,
            activeUserCount = 20,
        ),
        SupportedLanguage(
            code = "fa",
            name = "Persian",
            localName = "فارسی",
            articleCount = 1067492,
            pageCount = 6020141,
            activeUserCount = 5879,
        ),
        SupportedLanguage(
            code = "pcd",
            name = "Picard",
            localName = "Picard",
            articleCount = 6069,
            pageCount = 12108,
            activeUserCount = 41,
        ),
        SupportedLanguage(
            code = "pms",
            name = "Piedmontese",
            localName = "Piemontèis",
            articleCount = 70901,
            pageCount = 103351,
            activeUserCount = 48,
        ),
        SupportedLanguage(
            code = "pnt",
            name = "Pontic",
            localName = "Ποντιακά",
            articleCount = 538,
            pageCount = 2472,
            activeUserCount = 13,
        ),
        SupportedLanguage(
            code = "pt",
            name = "Portuguese",
            localName = "português",
            articleCount = 1164383,
            pageCount = 6045734,
            activeUserCount = 8009,
        ),
        SupportedLanguage(
            code = "pa",
            name = "Punjabi",
            localName = "ਪੰਜਾਬੀ",
            articleCount = 59384,
            pageCount = 191656,
            activeUserCount = 148,
        ),
        SupportedLanguage(
            code = "qu",
            name = "Quechua",
            localName = "Runa Simi",
            articleCount = 24429,
            pageCount = 58614,
            activeUserCount = 43,
        ),
        SupportedLanguage(
            code = "ro",
            name = "Romanian",
            localName = "română",
            articleCount = 538792,
            pageCount = 2985733,
            activeUserCount = 2166,
        ),
        SupportedLanguage(
            code = "rm",
            name = "Romansh",
            localName = "rumantsch",
            articleCount = 3820,
            pageCount = 9807,
            activeUserCount = 31,
        ),
        SupportedLanguage(
            code = "rn",
            name = "Rundi",
            localName = "ikirundi",
            articleCount = 703,
            pageCount = 2666,
            activeUserCount = 10,
        ),
        SupportedLanguage(
            code = "bxr",
            name = "Russia Buriat",
            localName = "буряад",
            articleCount = 2909,
            pageCount = 11223,
            activeUserCount = 21,
        ),
        SupportedLanguage(
            code = "rue",
            name = "Rusyn",
            localName = "русиньскый",
            articleCount = 10194,
            pageCount = 22616,
            activeUserCount = 45,
        ),
        SupportedLanguage(
            code = "szy",
            name = "Sakizaya",
            localName = "Sakizaya",
            articleCount = 2735,
            pageCount = 6359,
            activeUserCount = 16,
        ),
        SupportedLanguage(
            code = "sm",
            name = "Samoan",
            localName = "Gagana Samoa",
            articleCount = 1208,
            pageCount = 6179,
            activeUserCount = 11,
        ),
        SupportedLanguage(
            code = "bat-smg",
            name = "Samogitian",
            localName = "žemaitėška",
            articleCount = 17274,
            pageCount = 30072,
            activeUserCount = 31,
        ),
        SupportedLanguage(
            code = "sg",
            name = "Sango",
            localName = "Sängö",
            articleCount = 350,
            pageCount = 1952,
            activeUserCount = 10,
        ),
        SupportedLanguage(
            code = "sa",
            name = "Sanskrit",
            localName = "संस्कृतम्",
            articleCount = 12478,
            pageCount = 81957,
            activeUserCount = 45,
        ),
        SupportedLanguage(
            code = "sat",
            name = "Santali",
            localName = "ᱥᱟᱱᱛᱟᱲᱤ",
            articleCount = 14439,
            pageCount = 30757,
            activeUserCount = 34,
        ),
        SupportedLanguage(
            code = "skr",
            name = "Saraiki",
            localName = "سرائیکی",
            articleCount = 24438,
            pageCount = 29070,
            activeUserCount = 28,
        ),
        SupportedLanguage(
            code = "sc",
            name = "Sardinian",
            localName = "sardu",
            articleCount = 7772,
            pageCount = 17566,
            activeUserCount = 32,
        ),
        SupportedLanguage(
            code = "stq",
            name = "Saterland Frisian",
            localName = "Seeltersk",
            articleCount = 4130,
            pageCount = 10766,
            activeUserCount = 15,
        ),
        SupportedLanguage(
            code = "sco",
            name = "Scots",
            localName = "Scots",
            articleCount = 34274,
            pageCount = 138257,
            activeUserCount = 140,
        ),
        SupportedLanguage(
            code = "gd",
            name = "Scottish Gaelic",
            localName = "Gàidhlig",
            articleCount = 16023,
            pageCount = 32746,
            activeUserCount = 40,
        ),
        SupportedLanguage(
            code = "sr",
            name = "Serbian",
            localName = "српски / srpski",
            articleCount = 715896,
            pageCount = 4226797,
            activeUserCount = 2009,
        ),
        SupportedLanguage(
            code = "sh",
            name = "Serbo-Croatian",
            localName = "srpskohrvatski / српскохрватски",
            articleCount = 461379,
            pageCount = 4627557,
            activeUserCount = 349,
        ),
        SupportedLanguage(
            code = "shn",
            name = "Shan",
            localName = "တႆး",
            articleCount = 14562,
            pageCount = 35067,
            activeUserCount = 43,
        ),
        SupportedLanguage(
            code = "sn",
            name = "Shona",
            localName = "chiShona",
            articleCount = 11497,
            pageCount = 20497,
            activeUserCount = 27,
        ),
        SupportedLanguage(
            code = "scn",
            name = "Sicilian",
            localName = "sicilianu",
            articleCount = 26275,
            pageCount = 56121,
            activeUserCount = 67,
        ),
        SupportedLanguage(
            code = "szl",
            name = "Silesian",
            localName = "ślůnski",
            articleCount = 59849,
            pageCount = 76318,
            activeUserCount = 52,
        ),
        SupportedLanguage(
            code = "simple",
            name = "Simple English",
            localName = "Simple English",
            articleCount = 279110,
            pageCount = 927694,
            activeUserCount = 3937,
        ),
        SupportedLanguage(
            code = "sd",
            name = "Sindhi",
            localName = "سنڌي",
            articleCount = 20076,
            pageCount = 73053,
            activeUserCount = 49,
        ),
        SupportedLanguage(
            code = "si",
            name = "Sinhala",
            localName = "සිංහල",
            articleCount = 25012,
            pageCount = 170571,
            activeUserCount = 177,
        ),
        SupportedLanguage(
            code = "sk",
            name = "Slovak",
            localName = "slovenčina",
            articleCount = 258117,
            pageCount = 599112,
            activeUserCount = 1459,
        ),
        SupportedLanguage(
            code = "sl",
            name = "Slovenian",
            localName = "slovenščina",
            articleCount = 196483,
            pageCount = 502557,
            activeUserCount = 997,
        ),
        SupportedLanguage(
            code = "so",
            name = "Somali",
            localName = "Soomaaliga",
            articleCount = 10417,
            pageCount = 31320,
            activeUserCount = 157,
        ),
        SupportedLanguage(
            code = "azb",
            name = "South Azerbaijani",
            localName = "تۆرکجه",
            articleCount = 244552,
            pageCount = 580118,
            activeUserCount = 103,
        ),
        SupportedLanguage(
            code = "nr",
            name = "South Ndebele",
            localName = "isiNdebele seSewula",
            articleCount = 286,
            pageCount = 876,
            activeUserCount = 12,
        ),
        SupportedLanguage(
            code = "alt",
            name = "Southern Altai",
            localName = "алтай тил",
            articleCount = 1101,
            pageCount = 7087,
            activeUserCount = 17,
        ),
        SupportedLanguage(
            code = "dga",
            name = "Southern Dagaare",
            localName = "Dagaare",
            articleCount = 3053,
            pageCount = 6598,
            activeUserCount = 20,
        ),
        SupportedLanguage(
            code = "st",
            name = "Southern Sotho",
            localName = "Sesotho",
            articleCount = 1631,
            pageCount = 5589,
            activeUserCount = 35,
        ),
        SupportedLanguage(
            code = "srn",
            name = "Sranan Tongo",
            localName = "Sranantongo",
            articleCount = 1128,
            pageCount = 2733,
            activeUserCount = 10,
        ),
        SupportedLanguage(
            code = "zgh",
            name = "Standard Moroccan Tamazight",
            localName = "ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ",
            articleCount = 12124,
            pageCount = 47103,
            activeUserCount = 84,
        ),
        SupportedLanguage(
            code = "su",
            name = "Sundanese",
            localName = "Sunda",
            articleCount = 62253,
            pageCount = 99871,
            activeUserCount = 65,
        ),
        SupportedLanguage(
            code = "sw",
            name = "Swahili",
            localName = "Kiswahili",
            articleCount = 105600,
            pageCount = 211349,
            activeUserCount = 278,
        ),
        SupportedLanguage(
            code = "ss",
            name = "Swati",
            localName = "SiSwati",
            articleCount = 1134,
            pageCount = 3465,
            activeUserCount = 12,
        ),
        SupportedLanguage(
            code = "syl",
            name = "Sylheti",
            localName = "ꠍꠤꠟꠐꠤ",
            articleCount = 1215,
            pageCount = 6339,
            activeUserCount = 17,
        ),
        SupportedLanguage(
            code = "shi",
            name = "Tachelhit",
            localName = "Taclḥit",
            articleCount = 10883,
            pageCount = 14952,
            activeUserCount = 21,
        ),
        SupportedLanguage(
            code = "tl",
            name = "Tagalog",
            localName = "Tagalog",
            articleCount = 48741,
            pageCount = 248302,
            activeUserCount = 279,
        ),
        SupportedLanguage(
            code = "ty",
            name = "Tahitian",
            localName = "reo tahiti",
            articleCount = 1249,
            pageCount = 3069,
            activeUserCount = 5,
        ),
        SupportedLanguage(
            code = "tdd",
            name = "Tai Nuea",
            localName = "ᥖᥭᥰ ᥖᥬᥲ ᥑᥨᥒᥰ",
            articleCount = 448,
            pageCount = 2343,
            activeUserCount = 13,
        ),
        SupportedLanguage(
            code = "tg",
            name = "Tajik",
            localName = "тоҷикӣ",
            articleCount = 116522,
            pageCount = 284224,
            activeUserCount = 192,
        ),
        SupportedLanguage(
            code = "tly",
            name = "Talysh",
            localName = "tolışi",
            articleCount = 10081,
            pageCount = 13891,
            activeUserCount = 25,
        ),
        SupportedLanguage(
            code = "ta",
            name = "Tamil",
            localName = "தமிழ்",
            articleCount = 180773,
            pageCount = 614924,
            activeUserCount = 587,
        ),
        SupportedLanguage(
            code = "roa-tara",
            name = "Tarantino",
            localName = "tarandíne",
            articleCount = 9505,
            pageCount = 18692,
            activeUserCount = 18,
        ),
        SupportedLanguage(
            code = "trv",
            name = "Taroko",
            localName = "Seediq",
            articleCount = 1201,
            pageCount = 2214,
            activeUserCount = 9,
        ),
        SupportedLanguage(
            code = "tt",
            name = "Tatar",
            localName = "татарча / tatarça",
            articleCount = 609728,
            pageCount = 1359124,
            activeUserCount = 104,
        ),
        SupportedLanguage(
            code = "te",
            name = "Telugu",
            localName = "తెలుగు",
            articleCount = 120056,
            pageCount = 407992,
            activeUserCount = 476,
        ),
        SupportedLanguage(
            code = "tet",
            name = "Tetum",
            localName = "tetun",
            articleCount = 1384,
            pageCount = 3971,
            activeUserCount = 19,
        ),
        SupportedLanguage(
            code = "th",
            name = "Thai",
            localName = "ไทย",
            articleCount = 179608,
            pageCount = 1158421,
            activeUserCount = 3275,
        ),
        SupportedLanguage(
            code = "bo",
            name = "Tibetan",
            localName = "བོད་ཡིག",
            articleCount = 7979,
            pageCount = 21880,
            activeUserCount = 73,
        ),
        SupportedLanguage(
            code = "tig",
            name = "Tigre",
            localName = "ትግሬ",
            articleCount = 43,
            pageCount = 481,
            activeUserCount = 20,
        ),
        SupportedLanguage(
            code = "ti",
            name = "Tigrinya",
            localName = "ትግርኛ",
            articleCount = 335,
            pageCount = 3035,
            activeUserCount = 9,
        ),
        SupportedLanguage(
            code = "tpi",
            name = "Tok Pisin",
            localName = "Tok Pisin",
            articleCount = 1405,
            pageCount = 5755,
            activeUserCount = 16,
        ),
        SupportedLanguage(
            code = "tok",
            name = "Toki Pona",
            localName = "toki pona",
            articleCount = 3542,
            pageCount = 9406,
            activeUserCount = 127,
        ),
        SupportedLanguage(
            code = "to",
            name = "Tongan",
            localName = "lea faka-Tonga",
            articleCount = 2045,
            pageCount = 5526,
            activeUserCount = 13,
        ),
        SupportedLanguage(
            code = "ts",
            name = "Tsonga",
            localName = "Xitsonga",
            articleCount = 950,
            pageCount = 4226,
            activeUserCount = 12,
        ),
        SupportedLanguage(
            code = "tn",
            name = "Tswana",
            localName = "Setswana",
            articleCount = 3785,
            pageCount = 8195,
            activeUserCount = 22,
        ),
        SupportedLanguage(
            code = "tcy",
            name = "Tulu",
            localName = "ತುಳು",
            articleCount = 2992,
            pageCount = 18717,
            activeUserCount = 28,
        ),
        SupportedLanguage(
            code = "tum",
            name = "Tumbuka",
            localName = "chiTumbuka",
            articleCount = 18804,
            pageCount = 39260,
            activeUserCount = 29,
        ),
        SupportedLanguage(
            code = "tr",
            name = "Turkish",
            localName = "Türkçe",
            articleCount = 665455,
            pageCount = 3373163,
            activeUserCount = 5355,
        ),
        SupportedLanguage(
            code = "tk",
            name = "Turkmen",
            localName = "Türkmençe",
            articleCount = 7058,
            pageCount = 17459,
            activeUserCount = 60,
        ),
        SupportedLanguage(
            code = "tyv",
            name = "Tuvinian",
            localName = "тыва дыл",
            articleCount = 4125,
            pageCount = 14756,
            activeUserCount = 22,
        ),
        SupportedLanguage(
            code = "tw",
            name = "Twi",
            localName = "Twi",
            articleCount = 4618,
            pageCount = 8588,
            activeUserCount = 22,
        ),
        SupportedLanguage(
            code = "kcg",
            name = "Tyap",
            localName = "Tyap",
            articleCount = 1478,
            pageCount = 6458,
            activeUserCount = 24,
        ),
        SupportedLanguage(
            code = "udm",
            name = "Udmurt",
            localName = "удмурт",
            articleCount = 5913,
            pageCount = 20268,
            activeUserCount = 17,
        ),
        SupportedLanguage(
            code = "hsb",
            name = "Upper Sorbian",
            localName = "hornjoserbsce",
            articleCount = 14231,
            pageCount = 36428,
            activeUserCount = 33,
        ),
        SupportedLanguage(
            code = "ur",
            name = "Urdu",
            localName = "اردو",
            articleCount = 238935,
            pageCount = 2325613,
            activeUserCount = 387,
        ),
        SupportedLanguage(
            code = "ug",
            name = "Uyghur",
            localName = "ئۇيغۇرچە / Uyghurche",
            articleCount = 9683,
            pageCount = 17514,
            activeUserCount = 34,
        ),
        SupportedLanguage(
            code = "uz",
            name = "Uzbek",
            localName = "oʻzbekcha / ўзбекча",
            articleCount = 330294,
            pageCount = 1197292,
            activeUserCount = 801,
        ),
        SupportedLanguage(
            code = "ve",
            name = "Venda",
            localName = "Tshivenda",
            articleCount = 822,
            pageCount = 2375,
            activeUserCount = 12,
        ),
        SupportedLanguage(
            code = "vec",
            name = "Venetian",
            localName = "vèneto",
            articleCount = 69562,
            pageCount = 143335,
            activeUserCount = 55,
        ),
        SupportedLanguage(
            code = "vep",
            name = "Veps",
            localName = "vepsän kel’",
            articleCount = 7094,
            pageCount = 38436,
            activeUserCount = 31,
        ),
        SupportedLanguage(
            code = "vi",
            name = "Vietnamese",
            localName = "Tiếng Việt",
            articleCount = 1298013,
            pageCount = 7097463,
            activeUserCount = 4073,
        ),
        SupportedLanguage(
            code = "rmy",
            name = "Vlax Romani",
            localName = "romani čhib",
            articleCount = 756,
            pageCount = 2849,
            activeUserCount = 14,
        ),
        SupportedLanguage(
            code = "vo",
            name = "Volapük",
            localName = "Volapük",
            articleCount = 48034,
            pageCount = 165745,
            activeUserCount = 32,
        ),
        SupportedLanguage(
            code = "fiu-vro",
            name = "Võro",
            localName = "võro",
            articleCount = 6886,
            pageCount = 13035,
            activeUserCount = 13,
        ),
        SupportedLanguage(
            code = "wa",
            name = "Walloon",
            localName = "walon",
            articleCount = 12867,
            pageCount = 30832,
            activeUserCount = 31,
        ),
        SupportedLanguage(
            code = "war",
            name = "Waray",
            localName = "Winaray",
            articleCount = 1266850,
            pageCount = 2870369,
            activeUserCount = 84,
        ),
        SupportedLanguage(
            code = "guc",
            name = "Wayuu",
            localName = "wayuunaiki",
            articleCount = 695,
            pageCount = 1360,
            activeUserCount = 18,
        ),
        SupportedLanguage(
            code = "cy",
            name = "Welsh",
            localName = "Cymraeg",
            articleCount = 283980,
            pageCount = 539674,
            activeUserCount = 141,
        ),
        SupportedLanguage(
            code = "bdr",
            name = "West Coast Bajau",
            localName = "Bajau Sama",
            articleCount = 236,
            pageCount = 1323,
            activeUserCount = 12,
        ),
        SupportedLanguage(
            code = "vls",
            name = "West Flemish",
            localName = "West-Vlams",
            articleCount = 8276,
            pageCount = 22571,
            activeUserCount = 37,
        ),
        SupportedLanguage(
            code = "hyw",
            name = "Western Armenian",
            localName = "Արեւմտահայերէն",
            articleCount = 13360,
            pageCount = 28985,
            activeUserCount = 41,
        ),
        SupportedLanguage(
            code = "fy",
            name = "Western Frisian",
            localName = "Frysk",
            articleCount = 59230,
            pageCount = 177563,
            activeUserCount = 104,
        ),
        SupportedLanguage(
            code = "mrj",
            name = "Western Mari",
            localName = "кырык мары",
            articleCount = 10430,
            pageCount = 21298,
            activeUserCount = 12,
        ),
        SupportedLanguage(
            code = "pnb",
            name = "Western Punjabi",
            localName = "پنجابی",
            articleCount = 75004,
            pageCount = 141428,
            activeUserCount = 75,
        ),
        SupportedLanguage(
            code = "wo",
            name = "Wolof",
            localName = "Wolof",
            articleCount = 1745,
            pageCount = 5568,
            activeUserCount = 21,
        ),
        SupportedLanguage(
            code = "wuu",
            name = "Wu",
            localName = "吴语",
            articleCount = 47548,
            pageCount = 73407,
            activeUserCount = 107,
        ),
        SupportedLanguage(
            code = "xh",
            name = "Xhosa",
            localName = "isiXhosa",
            articleCount = 2322,
            pageCount = 5497,
            activeUserCount = 38,
        ),
        SupportedLanguage(
            code = "sah",
            name = "Yakut",
            localName = "саха тыла",
            articleCount = 17944,
            pageCount = 54361,
            activeUserCount = 51,
        ),
        SupportedLanguage(
            code = "yi",
            name = "Yiddish",
            localName = "ייִדיש",
            articleCount = 15648,
            pageCount = 44447,
            activeUserCount = 69,
        ),
        SupportedLanguage(
            code = "yo",
            name = "Yoruba",
            localName = "Yorùbá",
            articleCount = 36468,
            pageCount = 61352,
            activeUserCount = 53,
        ),
        SupportedLanguage(
            code = "zea",
            name = "Zeelandic",
            localName = "Zeêuws",
            articleCount = 7178,
            pageCount = 13656,
            activeUserCount = 38,
        ),
        SupportedLanguage(
            code = "za",
            name = "Zhuang",
            localName = "Vahcuengh",
            articleCount = 3006,
            pageCount = 5568,
            activeUserCount = 11,
        ),
        SupportedLanguage(
            code = "zu",
            name = "Zulu",
            localName = "isiZulu",
            articleCount = 11898,
            pageCount = 26293,
            activeUserCount = 42,
        ),
    )

val supportedLanguagesMap = supportedLanguages.associateBy { it.code }
