package com.anysoftkeyboard.janus.app.util

data class SupportedLanguage(
    val code: String,
    val name: String,
    val localName: String,
    val articleCount: Int,
    val pageCount: Int,
    val activeUserCount: Int
)

val supportedLanguages =
    listOf(
        SupportedLanguage(
            code = "en",
            name = "English",
            localName = "English",
            articleCount = 7116223,
            pageCount = 64800198,
            activeUserCount = 274246),
        SupportedLanguage(
            code = "ceb",
            name = "Cebuano",
            localName = "Cebuano",
            articleCount = 6115866,
            pageCount = 11231279,
            activeUserCount = 200),
        SupportedLanguage(
            code = "de",
            name = "German",
            localName = "Deutsch",
            articleCount = 3084222,
            pageCount = 8454293,
            activeUserCount = 35841),
        SupportedLanguage(
            code = "fr",
            name = "French",
            localName = "français",
            articleCount = 2729929,
            pageCount = 13801582,
            activeUserCount = 37568),
        SupportedLanguage(
            code = "sv",
            name = "Swedish",
            localName = "svenska",
            articleCount = 2621230,
            pageCount = 6350546,
            activeUserCount = 4749),
        SupportedLanguage(
            code = "nl",
            name = "Dutch",
            localName = "Nederlands",
            articleCount = 2207813,
            pageCount = 4751881,
            activeUserCount = 8369),
        SupportedLanguage(
            code = "es",
            name = "Spanish",
            localName = "español",
            articleCount = 2084945,
            pageCount = 8562621,
            activeUserCount = 38377),
        SupportedLanguage(
            code = "ru",
            name = "Russian",
            localName = "русский",
            articleCount = 2078492,
            pageCount = 8466961,
            activeUserCount = 7558),
        SupportedLanguage(
            code = "it",
            name = "Italian",
            localName = "italiano",
            articleCount = 1950746,
            pageCount = 8541291,
            activeUserCount = 29997),
        SupportedLanguage(
            code = "pl",
            name = "Polish",
            localName = "polski",
            articleCount = 1680049,
            pageCount = 3973362,
            activeUserCount = 10858),
        SupportedLanguage(
            code = "arz",
            name = "Egyptian Arabic",
            localName = "مصرى",
            articleCount = 1630289,
            pageCount = 2212911,
            activeUserCount = 331),
        SupportedLanguage(
            code = "zh",
            name = "Chinese",
            localName = "中文",
            articleCount = 1518434,
            pageCount = 8284608,
            activeUserCount = 16037),
        SupportedLanguage(
            code = "ja",
            name = "Japanese",
            localName = "日本語",
            articleCount = 1484625,
            pageCount = 4364511,
            activeUserCount = 25947),
        SupportedLanguage(
            code = "uk",
            name = "Ukrainian",
            localName = "українська",
            articleCount = 1402484,
            pageCount = 5210921,
            activeUserCount = 5734),
        SupportedLanguage(
            code = "vi",
            name = "Vietnamese",
            localName = "Tiếng Việt",
            articleCount = 1296998,
            pageCount = 10231361,
            activeUserCount = 3827),
        SupportedLanguage(
            code = "ab",
            name = "Abkhazian",
            localName = "аԥсшәа",
            articleCount = 6483,
            pageCount = 32917,
            activeUserCount = 21),
        SupportedLanguage(
            code = "ace",
            name = "Acehnese",
            localName = "Acèh",
            articleCount = 13004,
            pageCount = 27973,
            activeUserCount = 44),
        SupportedLanguage(
            code = "ady",
            name = "Adyghe",
            localName = "адыгабзэ",
            articleCount = 615,
            pageCount = 4736,
            activeUserCount = 17),
        SupportedLanguage(
            code = "af",
            name = "Afrikaans",
            localName = "Afrikaans",
            articleCount = 127671,
            pageCount = 434359,
            activeUserCount = 300),
        SupportedLanguage(
            code = "sq",
            name = "Albanian",
            localName = "shqip",
            articleCount = 104972,
            pageCount = 321670,
            activeUserCount = 522),
        SupportedLanguage(
            code = "als",
            name = "Alemannic",
            localName = "Alemannisch",
            articleCount = 31429,
            pageCount = 74751,
            activeUserCount = 129),
        SupportedLanguage(
            code = "am",
            name = "Amharic",
            localName = "አማርኛ",
            articleCount = 15482,
            pageCount = 46468,
            activeUserCount = 108),
        SupportedLanguage(
            code = "ami",
            name = "Amis",
            localName = "Pangcah",
            articleCount = 1146,
            pageCount = 2255,
            activeUserCount = 7),
        SupportedLanguage(
            code = "anp",
            name = "Angika",
            localName = "अंगिका",
            articleCount = 1670,
            pageCount = 5286,
            activeUserCount = 9),
        SupportedLanguage(
            code = "ar",
            name = "Arabic",
            localName = "العربية",
            articleCount = 1292721,
            pageCount = 9029737,
            activeUserCount = 6704),
        SupportedLanguage(
            code = "an",
            name = "Aragonese",
            localName = "aragonés",
            articleCount = 50947,
            pageCount = 185521,
            activeUserCount = 109),
        SupportedLanguage(
            code = "rki",
            name = "Arakanese",
            localName = "ရခိုင်",
            articleCount = 1086,
            pageCount = 3233,
            activeUserCount = 14),
        SupportedLanguage(
            code = "arc",
            name = "Aramaic",
            localName = "ܐܪܡܝܐ",
            articleCount = 1921,
            pageCount = 6375,
            activeUserCount = 22),
        SupportedLanguage(
            code = "hy",
            name = "Armenian",
            localName = "հայերեն",
            articleCount = 323348,
            pageCount = 1188358,
            activeUserCount = 700),
        SupportedLanguage(
            code = "roa-rup",
            name = "Aromanian",
            localName = "armãneashti",
            articleCount = 1390,
            pageCount = 4625,
            activeUserCount = 6),
        SupportedLanguage(
            code = "frp",
            name = "Arpitan",
            localName = "arpetan",
            articleCount = 5818,
            pageCount = 18068,
            activeUserCount = 29),
        SupportedLanguage(
            code = "as",
            name = "Assamese",
            localName = "অসমীয়া",
            articleCount = 21023,
            pageCount = 118344,
            activeUserCount = 222),
        SupportedLanguage(
            code = "ast",
            name = "Asturian",
            localName = "asturianu",
            articleCount = 138445,
            pageCount = 247662,
            activeUserCount = 205),
        SupportedLanguage(
            code = "tay",
            name = "Atayal",
            localName = "Tayal",
            articleCount = 2582,
            pageCount = 3311,
            activeUserCount = 18),
        SupportedLanguage(
            code = "atj",
            name = "Atikamekw",
            localName = "Atikamekw",
            articleCount = 2078,
            pageCount = 3291,
            activeUserCount = 5),
        SupportedLanguage(
            code = "av",
            name = "Avaric",
            localName = "авар",
            articleCount = 4005,
            pageCount = 18597,
            activeUserCount = 22),
        SupportedLanguage(
            code = "awa",
            name = "Awadhi",
            localName = "अवधी",
            articleCount = 2599,
            pageCount = 6756,
            activeUserCount = 22),
        SupportedLanguage(
            code = "ay",
            name = "Aymara",
            localName = "Aymar aru",
            articleCount = 5246,
            pageCount = 8920,
            activeUserCount = 25),
        SupportedLanguage(
            code = "az",
            name = "Azerbaijani",
            localName = "azərbaycanca",
            articleCount = 210521,
            pageCount = 643352,
            activeUserCount = 1088),
        SupportedLanguage(
            code = "ban",
            name = "Balinese",
            localName = "Basa Bali",
            articleCount = 35044,
            pageCount = 72477,
            activeUserCount = 97),
        SupportedLanguage(
            code = "bm",
            name = "Bambara",
            localName = "bamanankan",
            articleCount = 915,
            pageCount = 3323,
            activeUserCount = 15),
        SupportedLanguage(
            code = "bn",
            name = "Bangla",
            localName = "বাংলা",
            articleCount = 179829,
            pageCount = 1381891,
            activeUserCount = 2503),
        SupportedLanguage(
            code = "bjn",
            name = "Banjar",
            localName = "Banjar",
            articleCount = 11524,
            pageCount = 35178,
            activeUserCount = 66),
        SupportedLanguage(
            code = "map-bms",
            name = "Banyumasan",
            localName = "Basa Banyumasan",
            articleCount = 13940,
            pageCount = 30449,
            activeUserCount = 22),
        SupportedLanguage(
            code = "ba",
            name = "Bashkir",
            localName = "башҡортса",
            articleCount = 63921,
            pageCount = 183967,
            activeUserCount = 89),
        SupportedLanguage(
            code = "eu",
            name = "Basque",
            localName = "euskara",
            articleCount = 478230,
            pageCount = 1026136,
            activeUserCount = 1311),
        SupportedLanguage(
            code = "btm",
            name = "Batak Mandailing",
            localName = "Batak Mandailing",
            articleCount = 1200,
            pageCount = 2703,
            activeUserCount = 11),
        SupportedLanguage(
            code = "bbc",
            name = "Batak Toba",
            localName = "Batak Toba",
            articleCount = 1411,
            pageCount = 2508,
            activeUserCount = 13),
        SupportedLanguage(
            code = "bar",
            name = "Bavarian",
            localName = "Boarisch",
            articleCount = 27210,
            pageCount = 110619,
            activeUserCount = 69),
        SupportedLanguage(
            code = "be",
            name = "Belarusian",
            localName = "беларуская",
            articleCount = 258389,
            pageCount = 721983,
            activeUserCount = 394),
        SupportedLanguage(
            code = "be-tarask",
            name = "Belarusian (Taraškievica orthography)",
            localName = "беларуская (тарашкевіца)",
            articleCount = 90260,
            pageCount = 264426,
            activeUserCount = 284),
        SupportedLanguage(
            code = "bew",
            name = "Betawi",
            localName = "Betawi",
            articleCount = 3135,
            pageCount = 7543,
            activeUserCount = 27),
        SupportedLanguage(
            code = "bh",
            name = "Bhojpuri",
            localName = "भोजपुरी",
            articleCount = 8869,
            pageCount = 80805,
            activeUserCount = 44),
        SupportedLanguage(
            code = "bpy",
            name = "Bishnupriya",
            localName = "বিষ্ণুপ্রিয়া মণিপুরী",
            articleCount = 25092,
            pageCount = 63456,
            activeUserCount = 13),
        SupportedLanguage(
            code = "bi",
            name = "Bislama",
            localName = "Bislama",
            articleCount = 1481,
            pageCount = 3451,
            activeUserCount = 13),
        SupportedLanguage(
            code = "bs",
            name = "Bosnian",
            localName = "bosanski",
            articleCount = 96520,
            pageCount = 382825,
            activeUserCount = 307),
        SupportedLanguage(
            code = "br",
            name = "Breton",
            localName = "brezhoneg",
            articleCount = 90230,
            pageCount = 160790,
            activeUserCount = 146),
        SupportedLanguage(
            code = "bug",
            name = "Buginese",
            localName = "Basa Ugi",
            articleCount = 15952,
            pageCount = 20451,
            activeUserCount = 16),
        SupportedLanguage(
            code = "bg",
            name = "Bulgarian",
            localName = "български",
            articleCount = 307118,
            pageCount = 695750,
            activeUserCount = 2132),
        SupportedLanguage(
            code = "my",
            name = "Burmese",
            localName = "မြန်မာဘာသာ",
            articleCount = 109909,
            pageCount = 262593,
            activeUserCount = 317),
        SupportedLanguage(
            code = "zh-yue",
            name = "Cantonese",
            localName = "粵語",
            articleCount = 148745,
            pageCount = 336143,
            activeUserCount = 1021),
        SupportedLanguage(
            code = "ca",
            name = "Catalan",
            localName = "català",
            articleCount = 786627,
            pageCount = 1975578,
            activeUserCount = 2437),
        SupportedLanguage(
            code = "bcl",
            name = "Central Bikol",
            localName = "Bikol Central",
            articleCount = 21299,
            pageCount = 50158,
            activeUserCount = 56),
        SupportedLanguage(
            code = "dtp",
            name = "Central Dusun",
            localName = "Kadazandusun",
            articleCount = 1721,
            pageCount = 7250,
            activeUserCount = 18),
        SupportedLanguage(
            code = "knc",
            name = "Central Kanuri",
            localName = "Yerwa Kanuri",
            articleCount = 1593,
            pageCount = 2499,
            activeUserCount = 18),
        SupportedLanguage(
            code = "ckb",
            name = "Central Kurdish",
            localName = "کوردی",
            articleCount = 79408,
            pageCount = 252244,
            activeUserCount = 177),
        SupportedLanguage(
            code = "ch",
            name = "Chamorro",
            localName = "Chamoru",
            articleCount = 557,
            pageCount = 2592,
            activeUserCount = 14),
        SupportedLanguage(
            code = "cbk-zam",
            name = "Chavacano",
            localName = "Chavacano de Zamboanga",
            articleCount = 3235,
            pageCount = 8993,
            activeUserCount = 12),
        SupportedLanguage(
            code = "ce",
            name = "Chechen",
            localName = "нохчийн",
            articleCount = 693435,
            pageCount = 1327834,
            activeUserCount = 78),
        SupportedLanguage(
            code = "chr",
            name = "Cherokee",
            localName = "ᏣᎳᎩ",
            articleCount = 1002,
            pageCount = 4032,
            activeUserCount = 26),
        SupportedLanguage(
            code = "chy",
            name = "Cheyenne",
            localName = "Tsetsêhestâhese",
            articleCount = 721,
            pageCount = 2301,
            activeUserCount = 14),
        SupportedLanguage(
            code = "cu",
            name = "Church Slavic",
            localName = "словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ",
            articleCount = 1317,
            pageCount = 5893,
            activeUserCount = 18),
        SupportedLanguage(
            code = "cv",
            name = "Chuvash",
            localName = "чӑвашла",
            articleCount = 58326,
            pageCount = 121679,
            activeUserCount = 53),
        SupportedLanguage(
            code = "ksh",
            name = "Colognian",
            localName = "Ripoarisch",
            articleCount = 3038,
            pageCount = 10797,
            activeUserCount = 18),
        SupportedLanguage(
            code = "kw",
            name = "Cornish",
            localName = "kernowek",
            articleCount = 7097,
            pageCount = 14765,
            activeUserCount = 35),
        SupportedLanguage(
            code = "co",
            name = "Corsican",
            localName = "corsu",
            articleCount = 8625,
            pageCount = 17959,
            activeUserCount = 44),
        SupportedLanguage(
            code = "crh",
            name = "Crimean Tatar",
            localName = "qırımtatarca",
            articleCount = 29636,
            pageCount = 57657,
            activeUserCount = 39),
        SupportedLanguage(
            code = "hr",
            name = "Croatian",
            localName = "hrvatski",
            articleCount = 228901,
            pageCount = 495031,
            activeUserCount = 1180),
        SupportedLanguage(
            code = "cs",
            name = "Czech",
            localName = "čeština",
            articleCount = 583435,
            pageCount = 1627016,
            activeUserCount = 5027),
        SupportedLanguage(
            code = "dag",
            name = "Dagbani",
            localName = "dagbanli",
            articleCount = 13408,
            pageCount = 24420,
            activeUserCount = 93),
        SupportedLanguage(
            code = "da",
            name = "Danish",
            localName = "dansk",
            articleCount = 312013,
            pageCount = 978595,
            activeUserCount = 1543),
        SupportedLanguage(
            code = "diq",
            name = "Dimli",
            localName = "Zazaki",
            articleCount = 42493,
            pageCount = 64069,
            activeUserCount = 84),
        SupportedLanguage(
            code = "din",
            name = "Dinka",
            localName = "Thuɔŋjäŋ",
            articleCount = 372,
            pageCount = 1115,
            activeUserCount = 7),
        SupportedLanguage(
            code = "dv",
            name = "Divehi",
            localName = "ދިވެހިބަސް",
            articleCount = 3192,
            pageCount = 12515,
            activeUserCount = 22),
        SupportedLanguage(
            code = "dty",
            name = "Doteli",
            localName = "डोटेली",
            articleCount = 3632,
            pageCount = 22261,
            activeUserCount = 16),
        SupportedLanguage(
            code = "dz",
            name = "Dzongkha",
            localName = "ཇོང་ཁ",
            articleCount = 377,
            pageCount = 5555,
            activeUserCount = 15),
        SupportedLanguage(
            code = "mhr",
            name = "Eastern Mari",
            localName = "олык марий",
            articleCount = 11328,
            pageCount = 31305,
            activeUserCount = 29),
        SupportedLanguage(
            code = "eml",
            name = "Emiliano-Romagnolo",
            localName = "emiliàn e rumagnòl",
            articleCount = 13802,
            pageCount = 36950,
            activeUserCount = 36),
        SupportedLanguage(
            code = "myv",
            name = "Erzya",
            localName = "эрзянь",
            articleCount = 7868,
            pageCount = 31562,
            activeUserCount = 22),
        SupportedLanguage(
            code = "eo",
            name = "Esperanto",
            localName = "Esperanto",
            articleCount = 379980,
            pageCount = 852426,
            activeUserCount = 475),
        SupportedLanguage(
            code = "et",
            name = "Estonian",
            localName = "eesti",
            articleCount = 256890,
            pageCount = 605766,
            activeUserCount = 1233),
        SupportedLanguage(
            code = "ee",
            name = "Ewe",
            localName = "eʋegbe",
            articleCount = 1267,
            pageCount = 4193,
            activeUserCount = 13),
        SupportedLanguage(
            code = "ext",
            name = "Extremaduran",
            localName = "estremeñu",
            articleCount = 4090,
            pageCount = 9184,
            activeUserCount = 30),
        SupportedLanguage(
            code = "fat",
            name = "Fanti",
            localName = "mfantse",
            articleCount = 1762,
            pageCount = 4726,
            activeUserCount = 9),
        SupportedLanguage(
            code = "fo",
            name = "Faroese",
            localName = "føroyskt",
            articleCount = 14179,
            pageCount = 41064,
            activeUserCount = 50),
        SupportedLanguage(
            code = "hif",
            name = "Fiji Hindi",
            localName = "Fiji Hindi",
            articleCount = 12098,
            pageCount = 55412,
            activeUserCount = 61),
        SupportedLanguage(
            code = "fj",
            name = "Fijian",
            localName = "Na Vosa Vakaviti",
            articleCount = 1646,
            pageCount = 4414,
            activeUserCount = 16),
        SupportedLanguage(
            code = "fi",
            name = "Finnish",
            localName = "suomi",
            articleCount = 610529,
            pageCount = 1566107,
            activeUserCount = 3435),
        SupportedLanguage(
            code = "fon",
            name = "Fon",
            localName = "fɔ̀ngbè",
            articleCount = 3377,
            pageCount = 5125,
            activeUserCount = 30),
        SupportedLanguage(
            code = "gur",
            name = "Frafra",
            localName = "farefare",
            articleCount = 1332,
            pageCount = 2534,
            activeUserCount = 35),
        SupportedLanguage(
            code = "fur",
            name = "Friulian",
            localName = "furlan",
            articleCount = 4906,
            pageCount = 11223,
            activeUserCount = 26),
        SupportedLanguage(
            code = "ff",
            name = "Fula",
            localName = "Fulfulde",
            articleCount = 13465,
            pageCount = 28048,
            activeUserCount = 27),
        SupportedLanguage(
            code = "gag",
            name = "Gagauz",
            localName = "Gagauz",
            articleCount = 3014,
            pageCount = 7804,
            activeUserCount = 13),
        SupportedLanguage(
            code = "gl",
            name = "Galician",
            localName = "galego",
            articleCount = 228961,
            pageCount = 563234,
            activeUserCount = 480),
        SupportedLanguage(
            code = "gan",
            name = "Gan",
            localName = "贛語",
            articleCount = 6815,
            pageCount = 34474,
            activeUserCount = 31),
        SupportedLanguage(
            code = "lg",
            name = "Ganda",
            localName = "Luganda",
            articleCount = 4445,
            pageCount = 8759,
            activeUserCount = 31),
        SupportedLanguage(
            code = "ka",
            name = "Georgian",
            localName = "ქართული",
            articleCount = 189056,
            pageCount = 528337,
            activeUserCount = 499),
        SupportedLanguage(
            code = "gpe",
            name = "Ghanaian Pidgin",
            localName = "Ghanaian Pidgin",
            articleCount = 4241,
            pageCount = 22521,
            activeUserCount = 20),
        SupportedLanguage(
            code = "glk",
            name = "Gilaki",
            localName = "گیلکی",
            articleCount = 48292,
            pageCount = 57656,
            activeUserCount = 29),
        SupportedLanguage(
            code = "gom",
            name = "Goan Konkani",
            localName = "गोंयची कोंकणी / Gõychi Konknni",
            articleCount = 3643,
            pageCount = 8908,
            activeUserCount = 13),
        SupportedLanguage(
            code = "gor",
            name = "Gorontalo",
            localName = "Bahasa Hulontalo",
            articleCount = 14938,
            pageCount = 24527,
            activeUserCount = 44),
        SupportedLanguage(
            code = "got",
            name = "Gothic",
            localName = "𐌲𐌿𐍄𐌹𐍃𐌺",
            articleCount = 1004,
            pageCount = 3974,
            activeUserCount = 19),
        SupportedLanguage(
            code = "el",
            name = "Greek",
            localName = "Ελληνικά",
            articleCount = 262984,
            pageCount = 739399,
            activeUserCount = 2557),
        SupportedLanguage(
            code = "gn",
            name = "Guarani",
            localName = "Avañe'ẽ",
            articleCount = 5986,
            pageCount = 14062,
            activeUserCount = 30),
        SupportedLanguage(
            code = "gcr",
            name = "Guianan Creole",
            localName = "kriyòl gwiyannen",
            articleCount = 1075,
            pageCount = 2673,
            activeUserCount = 5),
        SupportedLanguage(
            code = "gu",
            name = "Gujarati",
            localName = "ગુજરાતી",
            articleCount = 30786,
            pageCount = 135077,
            activeUserCount = 110),
        SupportedLanguage(
            code = "guw",
            name = "Gun",
            localName = "gungbe",
            articleCount = 1562,
            pageCount = 2782,
            activeUserCount = 6),
        SupportedLanguage(
            code = "ht",
            name = "Haitian Creole",
            localName = "Kreyòl ayisyen",
            articleCount = 71495,
            pageCount = 92995,
            activeUserCount = 86),
        SupportedLanguage(
            code = "hak",
            name = "Hakka Chinese",
            localName = "客家語 / Hak-kâ-ngî",
            articleCount = 10387,
            pageCount = 19924,
            activeUserCount = 24),
        SupportedLanguage(
            code = "ha",
            name = "Hausa",
            localName = "Hausa",
            articleCount = 79916,
            pageCount = 119313,
            activeUserCount = 243),
        SupportedLanguage(
            code = "haw",
            name = "Hawaiian",
            localName = "Hawaiʻi",
            articleCount = 2969,
            pageCount = 6206,
            activeUserCount = 56),
        SupportedLanguage(
            code = "he",
            name = "Hebrew",
            localName = "עברית",
            articleCount = 388415,
            pageCount = 1633786,
            activeUserCount = 8577),
        SupportedLanguage(
            code = "hi",
            name = "Hindi",
            localName = "हिन्दी",
            articleCount = 167093,
            pageCount = 1383341,
            activeUserCount = 1247),
        SupportedLanguage(
            code = "hu",
            name = "Hungarian",
            localName = "magyar",
            articleCount = 564630,
            pageCount = 1604868,
            activeUserCount = 3364),
        SupportedLanguage(
            code = "iba",
            name = "Iban",
            localName = "Jaku Iban",
            articleCount = 1924,
            pageCount = 5210,
            activeUserCount = 22),
        SupportedLanguage(
            code = "is",
            name = "Icelandic",
            localName = "íslenska",
            articleCount = 61004,
            pageCount = 159214,
            activeUserCount = 232),
        SupportedLanguage(
            code = "io",
            name = "Ido",
            localName = "Ido",
            articleCount = 60501,
            pageCount = 91972,
            activeUserCount = 67),
        SupportedLanguage(
            code = "igl",
            name = "Igala",
            localName = "Igala",
            articleCount = 941,
            pageCount = 1351,
            activeUserCount = 6),
        SupportedLanguage(
            code = "ig",
            name = "Igbo",
            localName = "Igbo",
            articleCount = 44187,
            pageCount = 60662,
            activeUserCount = 67),
        SupportedLanguage(
            code = "ilo",
            name = "Iloko",
            localName = "Ilokano",
            articleCount = 15444,
            pageCount = 70548,
            activeUserCount = 28),
        SupportedLanguage(
            code = "smn",
            name = "Inari Sami",
            localName = "anarâškielâ",
            articleCount = 6507,
            pageCount = 29112,
            activeUserCount = 26),
        SupportedLanguage(
            code = "id",
            name = "Indonesian",
            localName = "Bahasa Indonesia",
            articleCount = 759816,
            pageCount = 4194654,
            activeUserCount = 5919),
        SupportedLanguage(
            code = "inh",
            name = "Ingush",
            localName = "гӀалгӀай",
            articleCount = 2442,
            pageCount = 16366,
            activeUserCount = 28),
        SupportedLanguage(
            code = "ia",
            name = "Interlingua",
            localName = "interlingua",
            articleCount = 30176,
            pageCount = 46086,
            activeUserCount = 52),
        SupportedLanguage(
            code = "ie",
            name = "Interlingue",
            localName = "Interlingue",
            articleCount = 13419,
            pageCount = 17713,
            activeUserCount = 33),
        SupportedLanguage(
            code = "iu",
            name = "Inuktitut",
            localName = "ᐃᓄᒃᑎᑐᑦ / inuktitut",
            articleCount = 425,
            pageCount = 2945,
            activeUserCount = 28),
        SupportedLanguage(
            code = "ik",
            name = "Inupiaq",
            localName = "Iñupiatun",
            articleCount = 594,
            pageCount = 2807,
            activeUserCount = 11),
        SupportedLanguage(
            code = "ga",
            name = "Irish",
            localName = "Gaeilge",
            articleCount = 62801,
            pageCount = 112658,
            activeUserCount = 121),
        SupportedLanguage(
            code = "jam",
            name = "Jamaican Creole English",
            localName = "Patois",
            articleCount = 1730,
            pageCount = 3134,
            activeUserCount = 11),
        SupportedLanguage(
            code = "jv",
            name = "Javanese",
            localName = "Jawa",
            articleCount = 74837,
            pageCount = 185776,
            activeUserCount = 160),
        SupportedLanguage(
            code = "kbd",
            name = "Kabardian",
            localName = "адыгэбзэ",
            articleCount = 1640,
            pageCount = 7093,
            activeUserCount = 12),
        SupportedLanguage(
            code = "kbp",
            name = "Kabiye",
            localName = "Kabɩyɛ",
            articleCount = 1715,
            pageCount = 3450,
            activeUserCount = 5),
        SupportedLanguage(
            code = "kab",
            name = "Kabyle",
            localName = "Taqbaylit",
            articleCount = 7012,
            pageCount = 17909,
            activeUserCount = 31),
        SupportedLanguage(
            code = "xal",
            name = "Kalmyk",
            localName = "хальмг",
            articleCount = 1599,
            pageCount = 12392,
            activeUserCount = 13),
        SupportedLanguage(
            code = "kn",
            name = "Kannada",
            localName = "ಕನ್ನಡ",
            articleCount = 34317,
            pageCount = 158201,
            activeUserCount = 193),
        SupportedLanguage(
            code = "kaa",
            name = "Kara-Kalpak",
            localName = "Qaraqalpaqsha",
            articleCount = 11111,
            pageCount = 29974,
            activeUserCount = 37),
        SupportedLanguage(
            code = "krc",
            name = "Karachay-Balkar",
            localName = "къарачай-малкъар",
            articleCount = 2694,
            pageCount = 16772,
            activeUserCount = 19),
        SupportedLanguage(
            code = "ks",
            name = "Kashmiri",
            localName = "کٲشُر",
            articleCount = 8552,
            pageCount = 21081,
            activeUserCount = 37),
        SupportedLanguage(
            code = "csb",
            name = "Kashubian",
            localName = "kaszëbsczi",
            articleCount = 5504,
            pageCount = 8914,
            activeUserCount = 25),
        SupportedLanguage(
            code = "kk",
            name = "Kazakh",
            localName = "қазақша",
            articleCount = 241776,
            pageCount = 659374,
            activeUserCount = 401),
        SupportedLanguage(
            code = "km",
            name = "Khmer",
            localName = "ភាសាខ្មែរ",
            articleCount = 11892,
            pageCount = 36819,
            activeUserCount = 176),
        SupportedLanguage(
            code = "ki",
            name = "Kikuyu",
            localName = "Gĩkũyũ",
            articleCount = 1971,
            pageCount = 3760,
            activeUserCount = 17),
        SupportedLanguage(
            code = "rw",
            name = "Kinyarwanda",
            localName = "Ikinyarwanda",
            articleCount = 8920,
            pageCount = 17699,
            activeUserCount = 59),
        SupportedLanguage(
            code = "kge",
            name = "Komering",
            localName = "Kumoring",
            articleCount = 2856,
            pageCount = 4592,
            activeUserCount = 15),
        SupportedLanguage(
            code = "kv",
            name = "Komi",
            localName = "коми",
            articleCount = 5732,
            pageCount = 19856,
            activeUserCount = 24),
        SupportedLanguage(
            code = "koi",
            name = "Komi-Permyak",
            localName = "перем коми",
            articleCount = 3469,
            pageCount = 13516,
            activeUserCount = 12),
        SupportedLanguage(
            code = "kg",
            name = "Kongo",
            localName = "Kongo",
            articleCount = 1574,
            pageCount = 4034,
            activeUserCount = 17),
        SupportedLanguage(
            code = "ko",
            name = "Korean",
            localName = "한국어",
            articleCount = 734267,
            pageCount = 3493411,
            activeUserCount = 6949),
        SupportedLanguage(
            code = "avk",
            name = "Kotava",
            localName = "Kotava",
            articleCount = 29900,
            pageCount = 36352,
            activeUserCount = 22),
        SupportedLanguage(
            code = "ku",
            name = "Kurdish",
            localName = "kurdî",
            articleCount = 90972,
            pageCount = 290594,
            activeUserCount = 140),
        SupportedLanguage(
            code = "kus",
            name = "Kusaal",
            localName = "Kʋsaal",
            articleCount = 1255,
            pageCount = 1846,
            activeUserCount = 10),
        SupportedLanguage(
            code = "ky",
            name = "Kyrgyz",
            localName = "кыргызча",
            articleCount = 76127,
            pageCount = 120695,
            activeUserCount = 112),
        SupportedLanguage(
            code = "lld",
            name = "Ladin",
            localName = "Ladin",
            articleCount = 180829,
            pageCount = 188200,
            activeUserCount = 37),
        SupportedLanguage(
            code = "lad",
            name = "Ladino",
            localName = "Ladino",
            articleCount = 3910,
            pageCount = 12662,
            activeUserCount = 22),
        SupportedLanguage(
            code = "lbe",
            name = "Lak",
            localName = "лакку",
            articleCount = 1100,
            pageCount = 16013,
            activeUserCount = 11),
        SupportedLanguage(
            code = "lo",
            name = "Lao",
            localName = "ລາວ",
            articleCount = 5281,
            pageCount = 15863,
            activeUserCount = 73),
        SupportedLanguage(
            code = "ltg",
            name = "Latgalian",
            localName = "latgaļu",
            articleCount = 1112,
            pageCount = 3210,
            activeUserCount = 13),
        SupportedLanguage(
            code = "la",
            name = "Latin",
            localName = "Latina",
            articleCount = 140906,
            pageCount = 291442,
            activeUserCount = 207),
        SupportedLanguage(
            code = "lv",
            name = "Latvian",
            localName = "latviešu",
            articleCount = 140162,
            pageCount = 560288,
            activeUserCount = 580),
        SupportedLanguage(
            code = "lez",
            name = "Lezghian",
            localName = "лезги",
            articleCount = 4456,
            pageCount = 14977,
            activeUserCount = 12),
        SupportedLanguage(
            code = "lij",
            name = "Ligurian",
            localName = "Ligure",
            articleCount = 11469,
            pageCount = 28170,
            activeUserCount = 42),
        SupportedLanguage(
            code = "li",
            name = "Limburgish",
            localName = "Limburgs",
            articleCount = 15150,
            pageCount = 68656,
            activeUserCount = 26),
        SupportedLanguage(
            code = "ln",
            name = "Lingala",
            localName = "lingála",
            articleCount = 4862,
            pageCount = 11498,
            activeUserCount = 25),
        SupportedLanguage(
            code = "lfn",
            name = "Lingua Franca Nova",
            localName = "Lingua Franca Nova",
            articleCount = 4501,
            pageCount = 7208,
            activeUserCount = 26),
        SupportedLanguage(
            code = "zh-classical",
            name = "Literary Chinese",
            localName = "文言",
            articleCount = 13939,
            pageCount = 118292,
            activeUserCount = 81),
        SupportedLanguage(
            code = "lt",
            name = "Lithuanian",
            localName = "lietuvių",
            articleCount = 224591,
            pageCount = 561125,
            activeUserCount = 763),
        SupportedLanguage(
            code = "olo",
            name = "Livvi-Karelian",
            localName = "livvinkarjala",
            articleCount = 4662,
            pageCount = 14088,
            activeUserCount = 13),
        SupportedLanguage(
            code = "jbo",
            name = "Lojban",
            localName = "la .lojban.",
            articleCount = 1351,
            pageCount = 5805,
            activeUserCount = 17),
        SupportedLanguage(
            code = "lmo",
            name = "Lombard",
            localName = "lombard",
            articleCount = 79950,
            pageCount = 152825,
            activeUserCount = 98),
        SupportedLanguage(
            code = "nds",
            name = "Low German",
            localName = "Plattdüütsch",
            articleCount = 85783,
            pageCount = 185443,
            activeUserCount = 53),
        SupportedLanguage(
            code = "nds-nl",
            name = "Low Saxon",
            localName = "Nedersaksies",
            articleCount = 8073,
            pageCount = 21968,
            activeUserCount = 28),
        SupportedLanguage(
            code = "dsb",
            name = "Lower Sorbian",
            localName = "dolnoserbski",
            articleCount = 3429,
            pageCount = 11636,
            activeUserCount = 21),
        SupportedLanguage(
            code = "lb",
            name = "Luxembourgish",
            localName = "Lëtzebuergesch",
            articleCount = 66387,
            pageCount = 144498,
            activeUserCount = 116),
        SupportedLanguage(
            code = "mk",
            name = "Macedonian",
            localName = "македонски",
            articleCount = 157644,
            pageCount = 591881,
            activeUserCount = 371),
        SupportedLanguage(
            code = "mad",
            name = "Madurese",
            localName = "Madhurâ",
            articleCount = 2975,
            pageCount = 12786,
            activeUserCount = 77),
        SupportedLanguage(
            code = "mai",
            name = "Maithili",
            localName = "मैथिली",
            articleCount = 14259,
            pageCount = 45425,
            activeUserCount = 29),
        SupportedLanguage(
            code = "mg",
            name = "Malagasy",
            localName = "Malagasy",
            articleCount = 101772,
            pageCount = 259657,
            activeUserCount = 55),
        SupportedLanguage(
            code = "ms",
            name = "Malay",
            localName = "Bahasa Melayu",
            articleCount = 435514,
            pageCount = 1171149,
            activeUserCount = 2527),
        SupportedLanguage(
            code = "ml",
            name = "Malayalam",
            localName = "മലയാളം",
            articleCount = 87530,
            pageCount = 549447,
            activeUserCount = 474),
        SupportedLanguage(
            code = "mt",
            name = "Maltese",
            localName = "Malti",
            articleCount = 7680,
            pageCount = 23553,
            activeUserCount = 44),
        SupportedLanguage(
            code = "mni",
            name = "Manipuri",
            localName = "ꯃꯤꯇꯩ ꯂꯣꯟ",
            articleCount = 10455,
            pageCount = 17388,
            activeUserCount = 38),
        SupportedLanguage(
            code = "gv",
            name = "Manx",
            localName = "Gaelg",
            articleCount = 7056,
            pageCount = 39877,
            activeUserCount = 20),
        SupportedLanguage(
            code = "mr",
            name = "Marathi",
            localName = "मराठी",
            articleCount = 100973,
            pageCount = 326941,
            activeUserCount = 451),
        SupportedLanguage(
            code = "mzn",
            name = "Mazanderani",
            localName = "مازِرونی",
            articleCount = 64552,
            pageCount = 107396,
            activeUserCount = 57),
        SupportedLanguage(
            code = "min",
            name = "Minangkabau",
            localName = "Minangkabau",
            articleCount = 228733,
            pageCount = 473821,
            activeUserCount = 73),
        SupportedLanguage(
            code = "cdo",
            name = "Mindong",
            localName = "閩東語 / Mìng-dĕ̤ng-ngṳ̄",
            articleCount = 16704,
            pageCount = 33579,
            activeUserCount = 26),
        SupportedLanguage(
            code = "xmf",
            name = "Mingrelian",
            localName = "მარგალური",
            articleCount = 22007,
            pageCount = 41700,
            activeUserCount = 38),
        SupportedLanguage(
            code = "zh-min-nan",
            name = "Minnan",
            localName = "閩南語 / Bân-lâm-gí",
            articleCount = 433874,
            pageCount = 1075405,
            activeUserCount = 124),
        SupportedLanguage(
            code = "mwl",
            name = "Mirandese",
            localName = "Mirandés",
            articleCount = 4285,
            pageCount = 10734,
            activeUserCount = 21),
        SupportedLanguage(
            code = "mdf",
            name = "Moksha",
            localName = "мокшень",
            articleCount = 7619,
            pageCount = 23787,
            activeUserCount = 20),
        SupportedLanguage(
            code = "mnw",
            name = "Mon",
            localName = "ဘာသာမန်",
            articleCount = 1969,
            pageCount = 6811,
            activeUserCount = 11),
        SupportedLanguage(
            code = "mn",
            name = "Mongolian",
            localName = "монгол",
            articleCount = 26780,
            pageCount = 114028,
            activeUserCount = 313),
        SupportedLanguage(
            code = "ary",
            name = "Moroccan Arabic",
            localName = "الدارجة",
            articleCount = 10961,
            pageCount = 91477,
            activeUserCount = 55),
        SupportedLanguage(
            code = "mos",
            name = "Mossi",
            localName = "moore",
            articleCount = 1308,
            pageCount = 2093,
            activeUserCount = 7),
        SupportedLanguage(
            code = "mi",
            name = "Māori",
            localName = "Māori",
            articleCount = 8018,
            pageCount = 15390,
            activeUserCount = 20),
        SupportedLanguage(
            code = "nah",
            name = "Nahuatl",
            localName = "Nāhuatl",
            articleCount = 4291,
            pageCount = 13333,
            activeUserCount = 13),
        SupportedLanguage(
            code = "nv",
            name = "Navajo",
            localName = "Diné bizaad",
            articleCount = 22664,
            pageCount = 36577,
            activeUserCount = 23),
        SupportedLanguage(
            code = "nap",
            name = "Neapolitan",
            localName = "Napulitano",
            articleCount = 14943,
            pageCount = 24181,
            activeUserCount = 30),
        SupportedLanguage(
            code = "ne",
            name = "Nepali",
            localName = "नेपाली",
            articleCount = 29377,
            pageCount = 112275,
            activeUserCount = 137),
        SupportedLanguage(
            code = "new",
            name = "Newari",
            localName = "नेपाल भाषा",
            articleCount = 73122,
            pageCount = 222706,
            activeUserCount = 26),
        SupportedLanguage(
            code = "nia",
            name = "Nias",
            localName = "Li Niha",
            articleCount = 1767,
            pageCount = 4468,
            activeUserCount = 11),
        SupportedLanguage(
            code = "pcm",
            name = "Nigerian Pidgin",
            localName = "Naijá",
            articleCount = 1532,
            pageCount = 2791,
            activeUserCount = 15),
        SupportedLanguage(
            code = "nrm",
            name = "Norman",
            localName = "Nouormand",
            articleCount = 5057,
            pageCount = 10687,
            activeUserCount = 13),
        SupportedLanguage(
            code = "frr",
            name = "Northern Frisian",
            localName = "Nordfriisk",
            articleCount = 20699,
            pageCount = 51352,
            activeUserCount = 30),
        SupportedLanguage(
            code = "se",
            name = "Northern Sami",
            localName = "davvisámegiella",
            articleCount = 7905,
            pageCount = 21143,
            activeUserCount = 28),
        SupportedLanguage(
            code = "nso",
            name = "Northern Sotho",
            localName = "Sesotho sa Leboa",
            articleCount = 8782,
            pageCount = 11494,
            activeUserCount = 8),
        SupportedLanguage(
            code = "no",
            name = "Norwegian",
            localName = "norsk",
            articleCount = 668680,
            pageCount = 1887526,
            activeUserCount = 2234),
        SupportedLanguage(
            code = "nn",
            name = "Norwegian Nynorsk",
            localName = "norsk nynorsk",
            articleCount = 177104,
            pageCount = 398953,
            activeUserCount = 192),
        SupportedLanguage(
            code = "nov",
            name = "Novial",
            localName = "Novial",
            articleCount = 1909,
            pageCount = 4824,
            activeUserCount = 20),
        SupportedLanguage(
            code = "nup",
            name = "Nupe",
            localName = "Nupe",
            articleCount = 557,
            pageCount = 1158,
            activeUserCount = 16),
        SupportedLanguage(
            code = "ny",
            name = "Nyanja",
            localName = "Chi-Chewa",
            articleCount = 1099,
            pageCount = 5357,
            activeUserCount = 9),
        SupportedLanguage(
            code = "nqo",
            name = "N’Ko",
            localName = "ߒߞߏ",
            articleCount = 1588,
            pageCount = 3427,
            activeUserCount = 11),
        SupportedLanguage(
            code = "ann",
            name = "Obolo",
            localName = "Obolo",
            articleCount = 434,
            pageCount = 896,
            activeUserCount = 10),
        SupportedLanguage(
            code = "oc",
            name = "Occitan",
            localName = "occitan",
            articleCount = 90470,
            pageCount = 166518,
            activeUserCount = 206),
        SupportedLanguage(
            code = "or",
            name = "Odia",
            localName = "ଓଡ଼ିଆ",
            articleCount = 20196,
            pageCount = 85723,
            activeUserCount = 72),
        SupportedLanguage(
            code = "ang",
            name = "Old English",
            localName = "Ænglisc",
            articleCount = 5080,
            pageCount = 21469,
            activeUserCount = 60),
        SupportedLanguage(
            code = "om",
            name = "Oromo",
            localName = "Oromoo",
            articleCount = 1958,
            pageCount = 5328,
            activeUserCount = 24),
        SupportedLanguage(
            code = "os",
            name = "Ossetic",
            localName = "ирон",
            articleCount = 21479,
            pageCount = 76806,
            activeUserCount = 37),
        SupportedLanguage(
            code = "blk",
            name = "Pa'O",
            localName = "ပအိုဝ်ႏဘာႏသာႏ",
            articleCount = 2910,
            pageCount = 8817,
            activeUserCount = 5),
        SupportedLanguage(
            code = "pwn",
            name = "Paiwan",
            localName = "pinayuanan",
            articleCount = 376,
            pageCount = 636,
            activeUserCount = 4),
        SupportedLanguage(
            code = "pfl",
            name = "Palatine German",
            localName = "Pälzisch",
            articleCount = 2833,
            pageCount = 7076,
            activeUserCount = 13),
        SupportedLanguage(
            code = "pi",
            name = "Pali",
            localName = "पालि",
            articleCount = 302,
            pageCount = 1832,
            activeUserCount = 10),
        SupportedLanguage(
            code = "pam",
            name = "Pampanga",
            localName = "Kapampangan",
            articleCount = 10165,
            pageCount = 23286,
            activeUserCount = 22),
        SupportedLanguage(
            code = "pag",
            name = "Pangasinan",
            localName = "Pangasinan",
            articleCount = 2619,
            pageCount = 6740,
            activeUserCount = 11),
        SupportedLanguage(
            code = "rsk",
            name = "Pannonian Rusyn",
            localName = "руски",
            articleCount = 1044,
            pageCount = 2299,
            activeUserCount = 18),
        SupportedLanguage(
            code = "pap",
            name = "Papiamento",
            localName = "Papiamentu",
            articleCount = 5081,
            pageCount = 10539,
            activeUserCount = 22),
        SupportedLanguage(
            code = "ps",
            name = "Pashto",
            localName = "پښتو",
            articleCount = 20884,
            pageCount = 75383,
            activeUserCount = 68),
        SupportedLanguage(
            code = "pdc",
            name = "Pennsylvania German",
            localName = "Deitsch",
            articleCount = 2050,
            pageCount = 5926,
            activeUserCount = 32),
        SupportedLanguage(
            code = "fa",
            name = "Persian",
            localName = "فارسی",
            articleCount = 1066352,
            pageCount = 6011759,
            activeUserCount = 11175),
        SupportedLanguage(
            code = "pcd",
            name = "Picard",
            localName = "Picard",
            articleCount = 6048,
            pageCount = 12051,
            activeUserCount = 49),
        SupportedLanguage(
            code = "pms",
            name = "Piedmontese",
            localName = "Piemontèis",
            articleCount = 70792,
            pageCount = 103241,
            activeUserCount = 38),
        SupportedLanguage(
            code = "pnt",
            name = "Pontic",
            localName = "Ποντιακά",
            articleCount = 540,
            pageCount = 2478,
            activeUserCount = 16),
        SupportedLanguage(
            code = "pt",
            name = "Portuguese",
            localName = "português",
            articleCount = 1162638,
            pageCount = 6028469,
            activeUserCount = 7547),
        SupportedLanguage(
            code = "pa",
            name = "Punjabi",
            localName = "ਪੰਜਾਬੀ",
            articleCount = 59328,
            pageCount = 191128,
            activeUserCount = 132),
        SupportedLanguage(
            code = "qu",
            name = "Quechua",
            localName = "Runa Simi",
            articleCount = 24391,
            pageCount = 58514,
            activeUserCount = 43),
        SupportedLanguage(
            code = "ro",
            name = "Romanian",
            localName = "română",
            articleCount = 538026,
            pageCount = 2969217,
            activeUserCount = 2111),
        SupportedLanguage(
            code = "rm",
            name = "Romansh",
            localName = "rumantsch",
            articleCount = 3813,
            pageCount = 9788,
            activeUserCount = 23),
        SupportedLanguage(
            code = "rn",
            name = "Rundi",
            localName = "ikirundi",
            articleCount = 703,
            pageCount = 2666,
            activeUserCount = 9),
        SupportedLanguage(
            code = "bxr",
            name = "Russia Buriat",
            localName = "буряад",
            articleCount = 2912,
            pageCount = 11225,
            activeUserCount = 17),
        SupportedLanguage(
            code = "rue",
            name = "Rusyn",
            localName = "русиньскый",
            articleCount = 10179,
            pageCount = 22370,
            activeUserCount = 40),
        SupportedLanguage(
            code = "szy",
            name = "Sakizaya",
            localName = "Sakizaya",
            articleCount = 2735,
            pageCount = 6336,
            activeUserCount = 13),
        SupportedLanguage(
            code = "sm",
            name = "Samoan",
            localName = "Gagana Samoa",
            articleCount = 1208,
            pageCount = 6178,
            activeUserCount = 17),
        SupportedLanguage(
            code = "bat-smg",
            name = "Samogitian",
            localName = "žemaitėška",
            articleCount = 17274,
            pageCount = 30071,
            activeUserCount = 23),
        SupportedLanguage(
            code = "sg",
            name = "Sango",
            localName = "Sängö",
            articleCount = 446,
            pageCount = 2049,
            activeUserCount = 12),
        SupportedLanguage(
            code = "sa",
            name = "Sanskrit",
            localName = "संस्कृतम्",
            articleCount = 12470,
            pageCount = 81719,
            activeUserCount = 138),
        SupportedLanguage(
            code = "sat",
            name = "Santali",
            localName = "ᱥᱟᱱᱛᱟᱲᱤ",
            articleCount = 14313,
            pageCount = 30454,
            activeUserCount = 61),
        SupportedLanguage(
            code = "skr",
            name = "Saraiki",
            localName = "سرائیکی",
            articleCount = 24340,
            pageCount = 28841,
            activeUserCount = 16),
        SupportedLanguage(
            code = "sc",
            name = "Sardinian",
            localName = "sardu",
            articleCount = 7742,
            pageCount = 17500,
            activeUserCount = 34),
        SupportedLanguage(
            code = "stq",
            name = "Saterland Frisian",
            localName = "Seeltersk",
            articleCount = 4130,
            pageCount = 10832,
            activeUserCount = 20),
        SupportedLanguage(
            code = "sco",
            name = "Scots",
            localName = "Scots",
            articleCount = 34280,
            pageCount = 138214,
            activeUserCount = 124),
        SupportedLanguage(
            code = "gd",
            name = "Scottish Gaelic",
            localName = "Gàidhlig",
            articleCount = 16022,
            pageCount = 32635,
            activeUserCount = 36),
        SupportedLanguage(
            code = "sr",
            name = "Serbian",
            localName = "српски / srpski",
            articleCount = 714559,
            pageCount = 4222818,
            activeUserCount = 2174),
        SupportedLanguage(
            code = "sh",
            name = "Serbo-Croatian",
            localName = "srpskohrvatski / српскохрватски",
            articleCount = 461318,
            pageCount = 4627578,
            activeUserCount = 402),
        SupportedLanguage(
            code = "shn",
            name = "Shan",
            localName = "တႆး",
            articleCount = 14417,
            pageCount = 34694,
            activeUserCount = 119),
        SupportedLanguage(
            code = "sn",
            name = "Shona",
            localName = "chiShona",
            articleCount = 11499,
            pageCount = 20501,
            activeUserCount = 27),
        SupportedLanguage(
            code = "scn",
            name = "Sicilian",
            localName = "sicilianu",
            articleCount = 26274,
            pageCount = 56060,
            activeUserCount = 71),
        SupportedLanguage(
            code = "szl",
            name = "Silesian",
            localName = "ślůnski",
            articleCount = 59733,
            pageCount = 76182,
            activeUserCount = 42),
        SupportedLanguage(
            code = "simple",
            name = "Simple English",
            localName = "Simple English",
            articleCount = 278474,
            pageCount = 923650,
            activeUserCount = 4169),
        SupportedLanguage(
            code = "sd",
            name = "Sindhi",
            localName = "سنڌي",
            articleCount = 19805,
            pageCount = 71750,
            activeUserCount = 43),
        SupportedLanguage(
            code = "si",
            name = "Sinhala",
            localName = "සිංහල",
            articleCount = 24979,
            pageCount = 166765,
            activeUserCount = 162),
        SupportedLanguage(
            code = "sk",
            name = "Slovak",
            localName = "slovenčina",
            articleCount = 257516,
            pageCount = 597496,
            activeUserCount = 1307),
        SupportedLanguage(
            code = "sl",
            name = "Slovenian",
            localName = "slovenščina",
            articleCount = 196122,
            pageCount = 501209,
            activeUserCount = 736),
        SupportedLanguage(
            code = "so",
            name = "Somali",
            localName = "Soomaaliga",
            articleCount = 10212,
            pageCount = 30657,
            activeUserCount = 167),
        SupportedLanguage(
            code = "azb",
            name = "South Azerbaijani",
            localName = "تۆرکجه",
            articleCount = 244520,
            pageCount = 580065,
            activeUserCount = 118),
        SupportedLanguage(
            code = "nr",
            name = "South Ndebele",
            localName = "isiNdebele seSewula",
            articleCount = 282,
            pageCount = 868,
            activeUserCount = 14),
        SupportedLanguage(
            code = "alt",
            name = "Southern Altai",
            localName = "алтай тил",
            articleCount = 1101,
            pageCount = 7046,
            activeUserCount = 12),
        SupportedLanguage(
            code = "dga",
            name = "Southern Dagaare",
            localName = "Dagaare",
            articleCount = 3039,
            pageCount = 6573,
            activeUserCount = 18),
        SupportedLanguage(
            code = "st",
            name = "Southern Sotho",
            localName = "Sesotho",
            articleCount = 1580,
            pageCount = 5489,
            activeUserCount = 29),
        SupportedLanguage(
            code = "srn",
            name = "Sranan Tongo",
            localName = "Sranantongo",
            articleCount = 1128,
            pageCount = 2732,
            activeUserCount = 7),
        SupportedLanguage(
            code = "zgh",
            name = "Standard Moroccan Tamazight",
            localName = "ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ",
            articleCount = 12062,
            pageCount = 43267,
            activeUserCount = 80),
        SupportedLanguage(
            code = "su",
            name = "Sundanese",
            localName = "Sunda",
            articleCount = 62179,
            pageCount = 99777,
            activeUserCount = 70),
        SupportedLanguage(
            code = "sw",
            name = "Swahili",
            localName = "Kiswahili",
            articleCount = 103898,
            pageCount = 208927,
            activeUserCount = 538),
        SupportedLanguage(
            code = "ss",
            name = "Swati",
            localName = "SiSwati",
            articleCount = 1132,
            pageCount = 3461,
            activeUserCount = 14),
        SupportedLanguage(
            code = "syl",
            name = "Sylheti",
            localName = "ꠍꠤꠟꠐꠤ",
            articleCount = 1219,
            pageCount = 6298,
            activeUserCount = 11),
        SupportedLanguage(
            code = "shi",
            name = "Tachelhit",
            localName = "Taclḥit",
            articleCount = 10882,
            pageCount = 14945,
            activeUserCount = 22),
        SupportedLanguage(
            code = "tl",
            name = "Tagalog",
            localName = "Tagalog",
            articleCount = 48717,
            pageCount = 248129,
            activeUserCount = 266),
        SupportedLanguage(
            code = "ty",
            name = "Tahitian",
            localName = "reo tahiti",
            articleCount = 1249,
            pageCount = 3069,
            activeUserCount = 7),
        SupportedLanguage(
            code = "tdd",
            name = "Tai Nuea",
            localName = "ᥖᥭᥰ ᥖᥬᥲ ᥑᥨᥒᥰ",
            articleCount = 450,
            pageCount = 2207,
            activeUserCount = 4),
        SupportedLanguage(
            code = "tg",
            name = "Tajik",
            localName = "тоҷикӣ",
            articleCount = 116256,
            pageCount = 284093,
            activeUserCount = 140),
        SupportedLanguage(
            code = "tly",
            name = "Talysh",
            localName = "tolışi",
            articleCount = 10067,
            pageCount = 13880,
            activeUserCount = 28),
        SupportedLanguage(
            code = "ta",
            name = "Tamil",
            localName = "தமிழ்",
            articleCount = 179728,
            pageCount = 611847,
            activeUserCount = 580),
        SupportedLanguage(
            code = "roa-tara",
            name = "Tarantino",
            localName = "tarandíne",
            articleCount = 9497,
            pageCount = 18908,
            activeUserCount = 16),
        SupportedLanguage(
            code = "trv",
            name = "Taroko",
            localName = "Seediq",
            articleCount = 1201,
            pageCount = 2214,
            activeUserCount = 9),
        SupportedLanguage(
            code = "tt",
            name = "Tatar",
            localName = "татарча / tatarça",
            articleCount = 580244,
            pageCount = 1277606,
            activeUserCount = 103),
        SupportedLanguage(
            code = "te",
            name = "Telugu",
            localName = "తెలుగు",
            articleCount = 117952,
            pageCount = 402692,
            activeUserCount = 389),
        SupportedLanguage(
            code = "tet",
            name = "Tetum",
            localName = "tetun",
            articleCount = 1380,
            pageCount = 3979,
            activeUserCount = 15),
        SupportedLanguage(
            code = "th",
            name = "Thai",
            localName = "ไทย",
            articleCount = 178640,
            pageCount = 1152100,
            activeUserCount = 3114),
        SupportedLanguage(
            code = "bo",
            name = "Tibetan",
            localName = "བོད་ཡིག",
            articleCount = 7783,
            pageCount = 21461,
            activeUserCount = 77),
        SupportedLanguage(
            code = "tig",
            name = "Tigre",
            localName = "ትግሬ",
            articleCount = 43,
            pageCount = 484,
            activeUserCount = 14),
        SupportedLanguage(
            code = "ti",
            name = "Tigrinya",
            localName = "ትግርኛ",
            articleCount = 335,
            pageCount = 3032,
            activeUserCount = 8),
        SupportedLanguage(
            code = "tpi",
            name = "Tok Pisin",
            localName = "Tok Pisin",
            articleCount = 1407,
            pageCount = 5745,
            activeUserCount = 11),
        SupportedLanguage(
            code = "tok",
            name = "Toki Pona",
            localName = "toki pona",
            articleCount = 3414,
            pageCount = 9036,
            activeUserCount = 189),
        SupportedLanguage(
            code = "to",
            name = "Tongan",
            localName = "lea faka-Tonga",
            articleCount = 2043,
            pageCount = 5522,
            activeUserCount = 9),
        SupportedLanguage(
            code = "ts",
            name = "Tsonga",
            localName = "Xitsonga",
            articleCount = 950,
            pageCount = 4225,
            activeUserCount = 17),
        SupportedLanguage(
            code = "tn",
            name = "Tswana",
            localName = "Setswana",
            articleCount = 3771,
            pageCount = 8179,
            activeUserCount = 41),
        SupportedLanguage(
            code = "tcy",
            name = "Tulu",
            localName = "ತುಳು",
            articleCount = 2962,
            pageCount = 18307,
            activeUserCount = 31),
        SupportedLanguage(
            code = "tum",
            name = "Tumbuka",
            localName = "chiTumbuka",
            articleCount = 18799,
            pageCount = 39192,
            activeUserCount = 18),
        SupportedLanguage(
            code = "tr",
            name = "Turkish",
            localName = "Türkçe",
            articleCount = 658301,
            pageCount = 3391567,
            activeUserCount = 5444),
        SupportedLanguage(
            code = "tk",
            name = "Turkmen",
            localName = "Türkmençe",
            articleCount = 7050,
            pageCount = 17540,
            activeUserCount = 74),
        SupportedLanguage(
            code = "tyv",
            name = "Tuvinian",
            localName = "тыва дыл",
            articleCount = 4082,
            pageCount = 14638,
            activeUserCount = 17),
        SupportedLanguage(
            code = "tw",
            name = "Twi",
            localName = "Twi",
            articleCount = 4617,
            pageCount = 8593,
            activeUserCount = 17),
        SupportedLanguage(
            code = "kcg",
            name = "Tyap",
            localName = "Tyap",
            articleCount = 1471,
            pageCount = 6440,
            activeUserCount = 26),
        SupportedLanguage(
            code = "udm",
            name = "Udmurt",
            localName = "удмурт",
            articleCount = 5888,
            pageCount = 20197,
            activeUserCount = 35),
        SupportedLanguage(
            code = "hsb",
            name = "Upper Sorbian",
            localName = "hornjoserbsce",
            articleCount = 14221,
            pageCount = 36395,
            activeUserCount = 31),
        SupportedLanguage(
            code = "ur",
            name = "Urdu",
            localName = "اردو",
            articleCount = 237467,
            pageCount = 2312926,
            activeUserCount = 421),
        SupportedLanguage(
            code = "ug",
            name = "Uyghur",
            localName = "ئۇيغۇرچە / Uyghurche",
            articleCount = 9625,
            pageCount = 17032,
            activeUserCount = 30),
        SupportedLanguage(
            code = "uz",
            name = "Uzbek",
            localName = "oʻzbekcha / ўзбекча",
            articleCount = 323635,
            pageCount = 1182131,
            activeUserCount = 806),
        SupportedLanguage(
            code = "ve",
            name = "Venda",
            localName = "Tshivenda",
            articleCount = 822,
            pageCount = 2395,
            activeUserCount = 4),
        SupportedLanguage(
            code = "vec",
            name = "Venetian",
            localName = "vèneto",
            articleCount = 69533,
            pageCount = 143243,
            activeUserCount = 53),
        SupportedLanguage(
            code = "vep",
            name = "Veps",
            localName = "vepsän kel’",
            articleCount = 7082,
            pageCount = 38235,
            activeUserCount = 29),
        SupportedLanguage(
            code = "rmy",
            name = "Vlax Romani",
            localName = "romani čhib",
            articleCount = 756,
            pageCount = 2843,
            activeUserCount = 8),
        SupportedLanguage(
            code = "vo",
            name = "Volapük",
            localName = "Volapük",
            articleCount = 47171,
            pageCount = 164874,
            activeUserCount = 34),
        SupportedLanguage(
            code = "fiu-vro",
            name = "Võro",
            localName = "võro",
            articleCount = 6884,
            pageCount = 13054,
            activeUserCount = 28),
        SupportedLanguage(
            code = "wa",
            name = "Walloon",
            localName = "walon",
            articleCount = 12841,
            pageCount = 30748,
            activeUserCount = 45),
        SupportedLanguage(
            code = "war",
            name = "Waray",
            localName = "Winaray",
            articleCount = 1266853,
            pageCount = 2870712,
            activeUserCount = 110),
        SupportedLanguage(
            code = "guc",
            name = "Wayuu",
            localName = "wayuunaiki",
            articleCount = 694,
            pageCount = 1359,
            activeUserCount = 30),
        SupportedLanguage(
            code = "cy",
            name = "Welsh",
            localName = "Cymraeg",
            articleCount = 283912,
            pageCount = 537040,
            activeUserCount = 158),
        SupportedLanguage(
            code = "bdr",
            name = "West Coast Bajau",
            localName = "Bajau Sama",
            articleCount = 237,
            pageCount = 1323,
            activeUserCount = 11),
        SupportedLanguage(
            code = "vls",
            name = "West Flemish",
            localName = "West-Vlams",
            articleCount = 8258,
            pageCount = 22539,
            activeUserCount = 28),
        SupportedLanguage(
            code = "hyw",
            name = "Western Armenian",
            localName = "Արեւմտահայերէն",
            articleCount = 13323,
            pageCount = 28910,
            activeUserCount = 42),
        SupportedLanguage(
            code = "fy",
            name = "Western Frisian",
            localName = "Frysk",
            articleCount = 58961,
            pageCount = 176808,
            activeUserCount = 120),
        SupportedLanguage(
            code = "mrj",
            name = "Western Mari",
            localName = "кырык мары",
            articleCount = 10429,
            pageCount = 21230,
            activeUserCount = 14),
        SupportedLanguage(
            code = "pnb",
            name = "Western Punjabi",
            localName = "پنجابی",
            articleCount = 74866,
            pageCount = 140958,
            activeUserCount = 69),
        SupportedLanguage(
            code = "wo",
            name = "Wolof",
            localName = "Wolof",
            articleCount = 1744,
            pageCount = 5566,
            activeUserCount = 20),
        SupportedLanguage(
            code = "wuu",
            name = "Wu",
            localName = "吴语",
            articleCount = 47180,
            pageCount = 72218,
            activeUserCount = 131),
        SupportedLanguage(
            code = "xh",
            name = "Xhosa",
            localName = "isiXhosa",
            articleCount = 2319,
            pageCount = 5534,
            activeUserCount = 15),
        SupportedLanguage(
            code = "sah",
            name = "Yakut",
            localName = "саха тыла",
            articleCount = 17874,
            pageCount = 54163,
            activeUserCount = 60),
        SupportedLanguage(
            code = "yi",
            name = "Yiddish",
            localName = "ייִדיש",
            articleCount = 15642,
            pageCount = 44430,
            activeUserCount = 54),
        SupportedLanguage(
            code = "yo",
            name = "Yoruba",
            localName = "Yorùbá",
            articleCount = 36425,
            pageCount = 61282,
            activeUserCount = 84),
        SupportedLanguage(
            code = "zea",
            name = "Zeelandic",
            localName = "Zeêuws",
            articleCount = 7132,
            pageCount = 13587,
            activeUserCount = 44),
        SupportedLanguage(
            code = "za",
            name = "Zhuang",
            localName = "Vahcuengh",
            articleCount = 3006,
            pageCount = 5576,
            activeUserCount = 8),
        SupportedLanguage(
            code = "zu",
            name = "Zulu",
            localName = "isiZulu",
            articleCount = 11847,
            pageCount = 26210,
            activeUserCount = 39),
    )
